//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class BufferedWriter : Writer
    {
        public override void close(){}
        public override void flush(){}
        public BufferedWriter(Writer prm1){}
        public BufferedWriter(Writer prm1, int prm2){}
        public virtual void newLine(){}
        public override void write(char[] prm1, int prm2, int prm3){}
        public override void write(global::java.lang.String prm1, int prm2, int prm3){}
        public override void write(int prm1){}
    }
}
