//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class BufferedOutputStream : FilterOutputStream
    {
        public byte[] buf;
        public int count;
        public override void flush(){}
        public BufferedOutputStream(OutputStream prm1) : base(default(OutputStream)){}
        public BufferedOutputStream(OutputStream prm1, int prm2) : base(default(OutputStream)){}
        public override void write(int prm1){}
        public override void write(byte[] prm1, int prm2, int prm3){}
    }
}
