//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class CharArrayWriter : Writer
    {
        public char[] buf;
        public int count;
        public virtual CharArrayWriter append(global::java.lang.CharSequence prm1){return default(CharArrayWriter);}
        public virtual CharArrayWriter append(char prm1){return default(CharArrayWriter);}
        public virtual CharArrayWriter append(global::java.lang.CharSequence prm1, int prm2, int prm3){return default(CharArrayWriter);}
        public override void close(){}
        public override void flush(){}
        public CharArrayWriter(){}
        public CharArrayWriter(int prm1){}
        public virtual void reset(){}
        public virtual int size(){return default(int);}
        public virtual char[] toCharArray(){return default(char[]);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public override void write(char[] prm1, int prm2, int prm3){}
        public override void write(int prm1){}
        public override void write(global::java.lang.String prm1, int prm2, int prm3){}
        public virtual void writeTo(Writer prm1){}
    }
}
