//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class CharArrayReader : Reader
    {
        public char[] buf;
        public int count;
        public int markedPos;
        public int pos;
        public override void close(){}
        public CharArrayReader(char[] prm1){}
        public CharArrayReader(char[] prm1, int prm2, int prm3){}
        public override void mark(int prm1){}
        public override bool markSupported(){return default(bool);}
        public override int read(){return default(int);}
        public override int read(char[] prm1, int prm2, int prm3){return default(int);}
        public override bool ready(){return default(bool);}
        public override void reset(){}
        public override long skip(long prm1){return default(long);}
    }
}
