//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class CharConversionException : IOException
    {
        public CharConversionException(){}
        public CharConversionException(global::java.lang.String prm1){}
    }
}
