//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class DataInputStream : FilterInputStream, DataInput
    {
        public DataInputStream(InputStream prm1) : base(default(InputStream)){}
        public int read(byte[] prm1){return default(int);}
        public int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public bool readBoolean(){return default(bool);}
        public byte readByte(){return default(byte);}
        public char readChar(){return default(char);}
        public double readDouble(){return default(double);}
        public float readFloat(){return default(float);}
        public void readFully(byte[] prm1, int prm2, int prm3){}
        public void readFully(byte[] prm1){}
        public int readInt(){return default(int);}
        public global::java.lang.String readLine(){return default(global::java.lang.String);}
        public long readLong(){return default(long);}
        public short readShort(){return default(short);}
        public int readUnsignedByte(){return default(int);}
        public int readUnsignedShort(){return default(int);}
        public static global::java.lang.String readUTF(DataInput prm1){return default(global::java.lang.String);}
        public global::java.lang.String readUTF(){return default(global::java.lang.String);}
        public int skipBytes(int prm1){return default(int);}
    }
}
