//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class DataOutputStream : FilterOutputStream, DataOutput
    {
        public int written;
        public override void flush(){}
        public DataOutputStream(OutputStream prm1) : base(default(OutputStream)){}
        public int size(){return default(int);}
        public override void write(int prm1){}
        public override void write(byte[] prm1, int prm2, int prm3){}
        public void writeBoolean(bool prm1){}
        public void writeByte(int prm1){}
        public void writeBytes(global::java.lang.String prm1){}
        public void writeChar(int prm1){}
        public void writeChars(global::java.lang.String prm1){}
        public void writeDouble(double prm1){}
        public void writeFloat(float prm1){}
        public void writeInt(int prm1){}
        public void writeLong(long prm1){}
        public void writeShort(int prm1){}
        public void writeUTF(global::java.lang.String prm1){}
    }
}
