//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial interface DataInput
    {
        bool readBoolean();
        byte readByte();
        char readChar();
        double readDouble();
        float readFloat();
        void readFully(byte[] prm1);
        void readFully(byte[] prm1, int prm2, int prm3);
        int readInt();
        global::java.lang.String readLine();
        long readLong();
        short readShort();
        int readUnsignedByte();
        int readUnsignedShort();
        global::java.lang.String readUTF();
        int skipBytes(int prm1);
    }
}
