//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    internal partial class DeleteOnExitHook : global::java.lang.Object
    {
        public DeleteOnExitHook(){}
    }
}
