//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    internal partial class ExpiringCache : global::java.lang.Object
    {
        public ExpiringCache(){}
    }
}
