//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial interface Externalizable : Serializable
    {
        void readExternal(ObjectInput prm1);
        void writeExternal(ObjectOutput prm1);
    }
}
