//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class FileInputStream : InputStream
    {
        public override int available(){return default(int);}
        public override void close(){}
        protected override void finalize(){}
        public FileInputStream(File prm1){}
        public FileInputStream(global::java.lang.String prm1){}
        public FileInputStream(FileDescriptor prm1){}
        public override int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public override int read(byte[] prm1){return default(int);}
        public override int read(){return default(int);}
        public override long skip(long prm1){return default(long);}
        public global::java.nio.channels.FileChannel  Channel { get; private set;}
        public FileDescriptor  FD { get; private set;}
    }
}
