//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    internal abstract partial class FileSystem : global::java.lang.Object
    {
        public static int ACCESS_EXECUTE;
        public static int ACCESS_READ;
        public static int ACCESS_WRITE;
        public static int BA_DIRECTORY;
        public static int BA_EXISTS;
        public static int BA_HIDDEN;
        public static int BA_REGULAR;
        public static int SPACE_FREE;
        public static int SPACE_TOTAL;
        public static int SPACE_USABLE;
        public FileSystem(){}
        public virtual global::java.lang.String canonicalize(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual bool checkAccess(File prm1, int prm2){return default(bool);}
        public virtual int compare(File prm1, File prm2){return default(int);}
        public virtual bool createDirectory(File prm1){return default(bool);}
        public virtual bool createFileExclusively(global::java.lang.String prm1){return default(bool);}
        public virtual bool delete(File prm1){return default(bool);}
        public virtual global::java.lang.String fromURIPath(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual int getBooleanAttributes(File prm1){return default(int);}
        public virtual long getLastModifiedTime(File prm1){return default(long);}
        public virtual long getLength(File prm1){return default(long);}
        public virtual long getSpace(File prm1, int prm2){return default(long);}
        public virtual int hashCode(File prm1){return default(int);}
        public virtual bool isAbsolute(File prm1){return default(bool);}
        public virtual global::java.lang.String[] list(File prm1){return default(global::java.lang.String[]);}
        public virtual File[] listRoots(){return default(File[]);}
        public virtual global::java.lang.String normalize(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual int prefixLength(global::java.lang.String prm1){return default(int);}
        public virtual bool rename(File prm1, File prm2){return default(bool);}
        public virtual global::java.lang.String resolve(File prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String resolve(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        public virtual bool setLastModifiedTime(File prm1, long prm2){return default(bool);}
        public virtual bool setPermission(File prm1, int prm2, bool prm3, bool prm4){return default(bool);}
        public virtual bool setReadOnly(File prm1){return default(bool);}
        public global::java.lang.String  DefaultParent { get; private set;}
        public global::java.io.FileSystem  FileSystem___ { get; private set;}
        public char  PathSeparator { get; private set;}
        public char  Separator { get; private set;}
    }
}
