//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class FileReader : InputStreamReader
    {
        public FileReader(global::java.lang.String prm1) : base(default(InputStream), default(global::java.nio.charset.CharsetDecoder)){}
        public FileReader(File prm1) : base(default(InputStream), default(global::java.nio.charset.CharsetDecoder)){}
        public FileReader(FileDescriptor prm1) : base(default(InputStream), default(global::java.nio.charset.CharsetDecoder)){}
    }
}
