//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial interface FileFilter
    {
        bool accept(File prm1);
    }
}
