//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class FileNotFoundException : IOException
    {
        public FileNotFoundException(){}
        public FileNotFoundException(global::java.lang.String prm1){}
    }
}
