//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class FileWriter : OutputStreamWriter
    {
        public FileWriter(FileDescriptor prm1) : base(default(OutputStream), default(global::java.nio.charset.CharsetEncoder)){}
        public FileWriter(File prm1, bool prm2) : base(default(OutputStream), default(global::java.nio.charset.CharsetEncoder)){}
        public FileWriter(File prm1) : base(default(OutputStream), default(global::java.nio.charset.CharsetEncoder)){}
        public FileWriter(global::java.lang.String prm1, bool prm2) : base(default(OutputStream), default(global::java.nio.charset.CharsetEncoder)){}
        public FileWriter(global::java.lang.String prm1) : base(default(OutputStream), default(global::java.nio.charset.CharsetEncoder)){}
    }
}
