//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public abstract partial class InputStream : global::java.lang.Object, Closeable
    {
        public virtual int available(){return default(int);}
        public virtual void close(){}
        public InputStream(){}
        public virtual void mark(int prm1){}
        public virtual bool markSupported(){return default(bool);}
        public virtual int read(byte[] prm1){return default(int);}
        public virtual int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public virtual int read(){return default(int);}
        public virtual void reset(){}
        public virtual long skip(long prm1){return default(long);}
    }
}
