//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class InvalidClassException : ObjectStreamException
    {
        public global::java.lang.String classname;
        public InvalidClassException(global::java.lang.String prm1){}
        public InvalidClassException(global::java.lang.String prm1, global::java.lang.String prm2){}
        public global::java.lang.String  Message { get; private set;}
    }
}
