//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class InvalidObjectException : ObjectStreamException
    {
        public InvalidObjectException(global::java.lang.String prm1){}
    }
}
