//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class IOError : global::java.lang.Error
    {
        public IOError(global::java.lang.Throwable prm1){}
    }
}
