//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class IOException : global::java.lang.Exception
    {
        public IOException(global::java.lang.Throwable prm1){}
        public IOException(global::java.lang.String prm1, global::java.lang.Throwable prm2){}
        public IOException(global::java.lang.String prm1){}
        public IOException(){}
    }
}
