//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class LineNumberInputStream : FilterInputStream
    {
        public override int available(){return default(int);}
        public LineNumberInputStream(InputStream prm1) : base(default(InputStream)){}
        public override void mark(int prm1){}
        public override int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public override int read(){return default(int);}
        public override void reset(){}
        public virtual void setLineNumber(int prm1){}
        public override long skip(long prm1){return default(long);}
        public int  LineNumber { get; set;}
    }
}
