//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class LineNumberReader : BufferedReader
    {
        public LineNumberReader(Reader prm1) : base(default(Reader), default(int)){}
        public LineNumberReader(Reader prm1, int prm2) : base(default(Reader), default(int)){}
        public override void mark(int prm1){}
        public override int read(char[] prm1, int prm2, int prm3){return default(int);}
        public override int read(){return default(int);}
        public override global::java.lang.String readLine(){return default(global::java.lang.String);}
        public override void reset(){}
        public virtual void setLineNumber(int prm1){}
        public override long skip(long prm1){return default(long);}
        public int  LineNumber { get; set;}
    }
}
