//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class NotSerializableException : ObjectStreamException
    {
        public NotSerializableException(global::java.lang.String prm1){}
        public NotSerializableException(){}
    }
}
