//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class ObjectStreamClass : global::java.lang.Object, Serializable
    {
        public static ObjectStreamField[] NO_FIELDS;
        public ObjectStreamClass(){}
        public virtual global::java.lang.Class<global::System.Object> forClass(){return default(global::java.lang.Class<global::System.Object>);}
        public virtual ObjectStreamField getField(global::java.lang.String prm1){return default(ObjectStreamField);}
        public static ObjectStreamClass lookup(global::java.lang.Class<global::System.Object> prm1){return default(ObjectStreamClass);}
        public static ObjectStreamClass lookupAny(global::java.lang.Class<global::System.Object> prm1){return default(ObjectStreamClass);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public ObjectStreamField[]  Fields { get; private set;}
        public global::java.lang.String  Name { get; private set;}
        public long  SerialVersionUID { get; private set;}
    }
}
