//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial interface ObjectStreamConstants
    {
    }
}
