//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class ObjectInputStream : InputStream, ObjectInput, ObjectStreamConstants
    {
        public abstract partial class GetField : global::java.lang.Object
        {
            public virtual bool defaulted(global::java.lang.String prm1){return default(bool);}
            public virtual long get(global::java.lang.String prm1, long prm2){return default(long);}
            public virtual int get(global::java.lang.String prm1, int prm2){return default(int);}
            public virtual short get(global::java.lang.String prm1, short prm2){return default(short);}
            public virtual float get(global::java.lang.String prm1, float prm2){return default(float);}
            public virtual double get(global::java.lang.String prm1, double prm2){return default(double);}
            public virtual global::System.Object get(global::java.lang.String prm1, global::System.Object prm2){return default(global::System.Object);}
            public virtual bool get(global::java.lang.String prm1, bool prm2){return default(bool);}
            public virtual byte get(global::java.lang.String prm1, byte prm2){return default(byte);}
            public virtual char get(global::java.lang.String prm1, char prm2){return default(char);}
            public GetField(){}
            public global::java.io.ObjectStreamClass  ObjectStreamClass { get; private set;}
        }
        public override int available(){return default(int);}
        public override void close(){}
        public virtual void defaultReadObject(){}
        protected virtual bool enableResolveObject(bool prm1){return default(bool);}
        public ObjectInputStream(InputStream prm1){}
        public ObjectInputStream(){}
        public override int read(){return default(int);}
        public override int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public virtual bool readBoolean(){return default(bool);}
        public virtual byte readByte(){return default(byte);}
        public virtual char readChar(){return default(char);}
        protected virtual ObjectStreamClass readClassDescriptor(){return default(ObjectStreamClass);}
        public virtual double readDouble(){return default(double);}
        public virtual ObjectInputStream.GetField readFields(){return default(ObjectInputStream.GetField);}
        public virtual float readFloat(){return default(float);}
        public virtual void readFully(byte[] prm1){}
        public virtual void readFully(byte[] prm1, int prm2, int prm3){}
        public virtual int readInt(){return default(int);}
        public virtual global::java.lang.String readLine(){return default(global::java.lang.String);}
        public virtual long readLong(){return default(long);}
        public global::System.Object readObject(){return default(global::System.Object);}
        protected virtual global::System.Object readObjectOverride(){return default(global::System.Object);}
        public virtual short readShort(){return default(short);}
        protected virtual void readStreamHeader(){}
        public virtual global::System.Object readUnshared(){return default(global::System.Object);}
        public virtual int readUnsignedByte(){return default(int);}
        public virtual int readUnsignedShort(){return default(int);}
        public virtual global::java.lang.String readUTF(){return default(global::java.lang.String);}
        public virtual void registerValidation(ObjectInputValidation prm1, int prm2){}
        protected virtual global::java.lang.Class<global::System.Object> resolveClass(ObjectStreamClass prm1){return default(global::java.lang.Class<global::System.Object>);}
        protected virtual global::System.Object resolveObject(global::System.Object prm1){return default(global::System.Object);}
        protected virtual global::java.lang.Class<global::System.Object> resolveProxyClass(global::java.lang.String[] prm1){return default(global::java.lang.Class<global::System.Object>);}
        public virtual int skipBytes(int prm1){return default(int);}
    }
}
