//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class OptionalDataException : ObjectStreamException
    {
        public bool eof;
        public int length;
        public OptionalDataException(){}
    }
}
