//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public abstract partial class OutputStream : global::java.lang.Object, Closeable, Flushable
    {
        public virtual void close(){}
        public virtual void flush(){}
        public OutputStream(){}
        public virtual void write(byte[] prm1, int prm2, int prm3){}
        public virtual void write(byte[] prm1){}
        public virtual void write(int prm1){}
    }
}
