//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class OutputStreamWriter : Writer
    {
        public override void close(){}
        public override void flush(){}
        public OutputStreamWriter(OutputStream prm1, global::java.nio.charset.CharsetEncoder prm2){}
        public OutputStreamWriter(OutputStream prm1, global::java.nio.charset.Charset prm2){}
        public OutputStreamWriter(OutputStream prm1){}
        public OutputStreamWriter(OutputStream prm1, global::java.lang.String prm2){}
        public override void write(char[] prm1, int prm2, int prm3){}
        public override void write(int prm1){}
        public override void write(global::java.lang.String prm1, int prm2, int prm3){}
        public global::java.lang.String  Encoding { get; private set;}
    }
}
