//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class PipedReader : Reader
    {
        public override void close(){}
        public virtual void connect(PipedWriter prm1){}
        public PipedReader(int prm1){}
        public PipedReader(){}
        public PipedReader(PipedWriter prm1, int prm2){}
        public PipedReader(PipedWriter prm1){}
        public override int read(char[] prm1, int prm2, int prm3){return default(int);}
        public override int read(){return default(int);}
        public override bool ready(){return default(bool);}
    }
}
