//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class PipedOutputStream : OutputStream
    {
        public override void close(){}
        public virtual void connect(PipedInputStream prm1){}
        public override void flush(){}
        public PipedOutputStream(PipedInputStream prm1){}
        public PipedOutputStream(){}
        public override void write(int prm1){}
        public override void write(byte[] prm1, int prm2, int prm3){}
    }
}
