//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class PrintStream : FilterOutputStream, global::java.lang.Appendable, Closeable
    {
        public virtual PrintStream append(global::java.lang.CharSequence prm1, int prm2, int prm3){return default(PrintStream);}
        public virtual PrintStream append(char prm1){return default(PrintStream);}
        public virtual PrintStream append(global::java.lang.CharSequence prm1){return default(PrintStream);}
        global::java.lang.Appendable global::java.lang.Appendable.append(global::java.lang.CharSequence prm1){return default(global::java.lang.Appendable);}
        global::java.lang.Appendable global::java.lang.Appendable.append(global::java.lang.CharSequence prm1, int prm2, int prm3){return default(global::java.lang.Appendable);}
        global::java.lang.Appendable global::java.lang.Appendable.append(char prm1){return default(global::java.lang.Appendable);}
        public virtual bool checkError(){return default(bool);}
        protected virtual void clearError(){}
        public override void close(){}
        public override void flush(){}
        public virtual PrintStream format(global::java.util.Locale prm1, global::java.lang.String prm2, global::System.Object[] prm3){return default(PrintStream);}
        public virtual PrintStream format(global::java.lang.String prm1, global::System.Object[] prm2){return default(PrintStream);}
        public PrintStream(OutputStream prm1) : base(default(OutputStream)){}
        public PrintStream(OutputStream prm1, bool prm2) : base(default(OutputStream)){}
        public PrintStream(OutputStream prm1, bool prm2, global::java.lang.String prm3) : base(default(OutputStream)){}
        public PrintStream(global::java.lang.String prm1) : base(default(OutputStream)){}
        public PrintStream(global::java.lang.String prm1, global::java.lang.String prm2) : base(default(OutputStream)){}
        public PrintStream(File prm1, global::java.lang.String prm2) : base(default(OutputStream)){}
        public PrintStream(File prm1) : base(default(OutputStream)){}
        public virtual void print(float prm1){}
        public virtual void print(long prm1){}
        public virtual void print(int prm1){}
        public virtual void print(char prm1){}
        public virtual void print(bool prm1){}
        public virtual void print(global::System.Object prm1){}
        public virtual void print(global::java.lang.String prm1){}
        public virtual void print(char[] prm1){}
        public virtual void print(double prm1){}
        public virtual PrintStream printf(global::java.lang.String prm1, global::System.Object[] prm2){return default(PrintStream);}
        public virtual PrintStream printf(global::java.util.Locale prm1, global::java.lang.String prm2, global::System.Object[] prm3){return default(PrintStream);}
        public virtual void println(char[] prm1){}
        public virtual void println(double prm1){}
        public virtual void println(float prm1){}
        public virtual void println(global::java.lang.String prm1){}
        public virtual void println(global::System.Object prm1){}
        public virtual void println(bool prm1){}
        public virtual void println(){}
        public virtual void println(char prm1){}
        public virtual void println(int prm1){}
        public virtual void println(long prm1){}
        protected virtual void setError(){}
        public override void write(byte[] prm1, int prm2, int prm3){}
        public override void write(int prm1){}
    }
}
