//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class SerializablePermission : global::java.security.BasicPermission
    {
        public SerializablePermission(global::java.lang.String prm1) : base(default(global::java.lang.String), default(global::java.lang.String)){}
        public SerializablePermission(global::java.lang.String prm1, global::java.lang.String prm2) : base(default(global::java.lang.String), default(global::java.lang.String)){}
    }
}
