//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    internal partial class SerialCallbackContext : global::java.lang.Object
    {
        public SerialCallbackContext(global::System.Object prm1, ObjectStreamClass prm2){}
        public virtual void setUsed(){}
        public ObjectStreamClass  Desc { get; private set;}
        public global::System.Object  Obj { get; private set;}
    }
}
