//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class StreamCorruptedException : ObjectStreamException
    {
        public StreamCorruptedException(global::java.lang.String prm1){}
        public StreamCorruptedException(){}
    }
}
