//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class StringWriter : Writer
    {
        public virtual StringWriter append(global::java.lang.CharSequence prm1, int prm2, int prm3){return default(StringWriter);}
        public virtual StringWriter append(char prm1){return default(StringWriter);}
        public virtual StringWriter append(global::java.lang.CharSequence prm1){return default(StringWriter);}
        public override void close(){}
        public override void flush(){}
        public StringWriter(){}
        public StringWriter(int prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public override void write(global::java.lang.String prm1, int prm2, int prm3){}
        public override void write(global::java.lang.String prm1){}
        public override void write(char[] prm1, int prm2, int prm3){}
        public override void write(int prm1){}
        public global::java.lang.StringBuffer  Buffer { get; private set;}
    }
}
