//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class StringReader : Reader
    {
        public override void close(){}
        public StringReader(global::java.lang.String prm1){}
        public override void mark(int prm1){}
        public override bool markSupported(){return default(bool);}
        public override int read(){return default(int);}
        public override int read(char[] prm1, int prm2, int prm3){return default(int);}
        public override bool ready(){return default(bool);}
        public override void reset(){}
        public override long skip(long prm1){return default(long);}
    }
}
