//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class SyncFailedException : IOException
    {
        public SyncFailedException(global::java.lang.String prm1){}
    }
}
