//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class UTFDataFormatException : IOException
    {
        public UTFDataFormatException(){}
        public UTFDataFormatException(global::java.lang.String prm1){}
    }
}
