//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    internal partial class Win32FileSystem : global::java.io.FileSystem
    {
        public override global::java.lang.String canonicalize(global::java.lang.String prm1){return default(global::java.lang.String);}
        protected virtual global::java.lang.String canonicalize0(global::java.lang.String prm1){return default(global::java.lang.String);}
        protected virtual global::java.lang.String canonicalizeWithPrefix(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        protected virtual global::java.lang.String canonicalizeWithPrefix0(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        public override bool checkAccess(File prm1, int prm2){return default(bool);}
        public override int compare(File prm1, File prm2){return default(int);}
        public override bool createDirectory(File prm1){return default(bool);}
        public override bool createFileExclusively(global::java.lang.String prm1){return default(bool);}
        public override bool delete(File prm1){return default(bool);}
        protected virtual bool delete0(File prm1){return default(bool);}
        public override global::java.lang.String fromURIPath(global::java.lang.String prm1){return default(global::java.lang.String);}
        public override int getBooleanAttributes(File prm1){return default(int);}
        protected virtual global::java.lang.String getDriveDirectory(int prm1){return default(global::java.lang.String);}
        public override long getLastModifiedTime(File prm1){return default(long);}
        public override long getLength(File prm1){return default(long);}
        public override long getSpace(File prm1, int prm2){return default(long);}
        public override int hashCode(File prm1){return default(int);}
        public override bool isAbsolute(File prm1){return default(bool);}
        public Win32FileSystem(){}
        public override global::java.lang.String[] list(File prm1){return default(global::java.lang.String[]);}
        public override File[] listRoots(){return default(File[]);}
        public override global::java.lang.String normalize(global::java.lang.String prm1){return default(global::java.lang.String);}
        public override int prefixLength(global::java.lang.String prm1){return default(int);}
        public override bool rename(File prm1, File prm2){return default(bool);}
        protected virtual bool rename0(File prm1, File prm2){return default(bool);}
        public override global::java.lang.String resolve(File prm1){return default(global::java.lang.String);}
        public override global::java.lang.String resolve(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        public override bool setLastModifiedTime(File prm1, long prm2){return default(bool);}
        public override bool setPermission(File prm1, int prm2, bool prm3, bool prm4){return default(bool);}
        public override bool setReadOnly(File prm1){return default(bool);}
        public global::java.lang.String  DefaultParent { get; private set;}
        public char  PathSeparator { get; private set;}
        public char  Separator { get; private set;}
    }
}
