//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.io
{
    public partial class WriteAbortedException : ObjectStreamException
    {
        public global::java.lang.Exception detail;
        public WriteAbortedException(global::java.lang.String prm1, global::java.lang.Exception prm2){}
        public global::java.lang.Throwable  Cause { get; private set;}
        public global::java.lang.String  Message { get; private set;}
    }
}
