//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class CacheResponse : global::java.lang.Object
    {
        public CacheResponse(){}
        public global::java.io.InputStream  Body { get; private set;}
        public global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>>  Headers { get; private set;}
    }
}
