//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class ConnectException : SocketException
    {
        public ConnectException(global::java.lang.String prm1){}
        public ConnectException(){}
    }
}
