//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class ContentHandler : global::java.lang.Object
    {
        public virtual global::System.Object getContent(URLConnection prm1){return default(global::System.Object);}
        public virtual global::System.Object getContent(URLConnection prm1, global::java.lang.Class<global::java.lang.Q>[] prm2){return default(global::System.Object);}
        public ContentHandler(){}
    }
}
