//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface CookiePolicy
    {
        bool shouldAccept(URI prm1, HttpCookie prm2);
    }
}
