//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class CookieHandler : global::java.lang.Object
    {
        public virtual global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>> get(URI prm1, global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>> prm2){return default(global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>>);}
        public CookieHandler(){}
        public virtual void put(URI prm1, global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>> prm2){}
        public static void setDefault(CookieHandler prm1){}
        public CookieHandler  Default { get; set;}
    }
}
