//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface CookieStore
    {
        void add(URI prm1, HttpCookie prm2);
        global::java.util.List<HttpCookie> get(URI prm1);
        bool remove(URI prm1, HttpCookie prm2);
        bool removeAll();
        global::java.util.List<HttpCookie>  Cookies { get;}
        global::java.util.List<URI>  URIs { get;}
    }
}
