//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class DefaultInterface : global::java.lang.Object
    {
        public DefaultInterface(){}
    }
}
