//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class DualStackPlainSocketImpl : AbstractPlainSocketImpl
    {
        public DualStackPlainSocketImpl(bool prm1){}
        public DualStackPlainSocketImpl(global::java.io.FileDescriptor prm1, bool prm2){}
    }
}
