//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class FactoryURLClassLoader : URLClassLoader
    {
        public FactoryURLClassLoader() : base(default(URL[]), default(global::java.lang.ClassLoader), default(URLStreamHandlerFactory)){}
        public global::java.lang.Class<global::java.lang.Q> loadClass(global::java.lang.String prm1, bool prm2){return default(global::java.lang.Class<global::java.lang.Q>);}
    }
}
