//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface FileNameMap
    {
        global::java.lang.String getContentTypeFor(global::java.lang.String prm1);
    }
}
