//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class HttpCookie : global::java.lang.Object, global::java.lang.Cloneable
    {
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public static bool domainMatches(global::java.lang.String prm1, global::java.lang.String prm2){return default(bool);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public virtual bool hasExpired(){return default(bool);}
        public override int hashCode(){return default(int);}
        public HttpCookie(global::java.lang.String prm1, global::java.lang.String prm2){}
        public static global::java.util.List<HttpCookie> parse(global::java.lang.String prm1){return default(global::java.util.List<HttpCookie>);}
        public virtual void setComment(global::java.lang.String prm1){}
        public virtual void setCommentURL(global::java.lang.String prm1){}
        public virtual void setDiscard(bool prm1){}
        public virtual void setDomain(global::java.lang.String prm1){}
        public virtual void setHttpOnly(bool prm1){}
        public virtual void setMaxAge(long prm1){}
        public virtual void setPath(global::java.lang.String prm1){}
        public virtual void setPortlist(global::java.lang.String prm1){}
        public virtual void setSecure(bool prm1){}
        public virtual void setValue(global::java.lang.String prm1){}
        public virtual void setVersion(int prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.lang.String  Comment { get; set;}
        public global::java.lang.String  CommentURL { get; set;}
        public bool  Discard { get; set;}
        public global::java.lang.String  Domain { get; set;}
        public bool  IsHttpOnly { get; set;}
        public long  MaxAge { get; set;}
        public global::java.lang.String  Name { get; private set;}
        public global::java.lang.String  Path { get; set;}
        public global::java.lang.String  Portlist { get; set;}
        public bool  Secure { get; set;}
        public global::java.lang.String  Value { get; set;}
        public int  Version { get; set;}
    }
}
