//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class HttpURLConnection : URLConnection
    {
        public int chunkLength;
        public int fixedContentLength;
        public long fixedContentLengthLong;
        public static int HTTP_ACCEPTED;
        public static int HTTP_BAD_GATEWAY;
        public static int HTTP_BAD_METHOD;
        public static int HTTP_BAD_REQUEST;
        public static int HTTP_CLIENT_TIMEOUT;
        public static int HTTP_CONFLICT;
        public static int HTTP_CREATED;
        public static int HTTP_ENTITY_TOO_LARGE;
        public static int HTTP_FORBIDDEN;
        public static int HTTP_GATEWAY_TIMEOUT;
        public static int HTTP_GONE;
        public static int HTTP_INTERNAL_ERROR;
        public static int HTTP_LENGTH_REQUIRED;
        public static int HTTP_MOVED_PERM;
        public static int HTTP_MOVED_TEMP;
        public static int HTTP_MULT_CHOICE;
        public static int HTTP_NO_CONTENT;
        public static int HTTP_NOT_ACCEPTABLE;
        public static int HTTP_NOT_AUTHORITATIVE;
        public static int HTTP_NOT_FOUND;
        public static int HTTP_NOT_IMPLEMENTED;
        public static int HTTP_NOT_MODIFIED;
        public static int HTTP_OK;
        public static int HTTP_PARTIAL;
        public static int HTTP_PAYMENT_REQUIRED;
        public static int HTTP_PRECON_FAILED;
        public static int HTTP_PROXY_AUTH;
        public static int HTTP_REQ_TOO_LONG;
        public static int HTTP_RESET;
        public static int HTTP_SEE_OTHER;
        public static int HTTP_SERVER_ERROR;
        public static int HTTP_UNAUTHORIZED;
        public static int HTTP_UNAVAILABLE;
        public static int HTTP_UNSUPPORTED_TYPE;
        public static int HTTP_USE_PROXY;
        public static int HTTP_VERSION;
        public bool instanceFollowRedirects;
        public global::java.lang.String method;
        public int responseCode;
        public global::java.lang.String responseMessage;
        public virtual void disconnect(){}
        public override global::java.lang.String getHeaderField(int prm1){return default(global::java.lang.String);}
        public override long getHeaderFieldDate(global::java.lang.String prm1, long prm2){return default(long);}
        public override global::java.lang.String getHeaderFieldKey(int prm1){return default(global::java.lang.String);}
        public HttpURLConnection(URL prm1) : base(default(URL)){}
        public virtual void setChunkedStreamingMode(int prm1){}
        public virtual void setFixedLengthStreamingMode(long prm1){}
        public virtual void setFixedLengthStreamingMode(int prm1){}
        public static void setFollowRedirects(bool prm1){}
        public virtual void setInstanceFollowRedirects(bool prm1){}
        public virtual void setRequestMethod(global::java.lang.String prm1){}
        public virtual bool usingProxy(){return default(bool);}
        public global::java.io.InputStream  ErrorStream { get; private set;}
        public bool  FollowRedirects { get; set;}
        public bool  InstanceFollowRedirects { get; set;}
        public global::java.security.Permission  Permission { get; private set;}
        public global::java.lang.String  RequestMethod { get; set;}
        public int  ResponseCode { get; private set;}
        public global::java.lang.String  ResponseMessage { get; private set;}
    }
}
