//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class InetAddressContainer : global::java.lang.Object
    {
        public InetAddressContainer(){}
    }
}
