//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class Inet6AddressImpl : global::java.lang.Object, InetAddressImpl
    {
        public Inet6AddressImpl(){}
        public virtual InetAddress anyLocalAddress(){return default(InetAddress);}
        public virtual global::java.lang.String getHostByAddr(byte[] prm1){return default(global::java.lang.String);}
        public virtual bool isReachable(InetAddress prm1, int prm2, NetworkInterface prm3, int prm4){return default(bool);}
        public virtual InetAddress[] lookupAllHostAddr(global::java.lang.String prm1){return default(InetAddress[]);}
        public virtual InetAddress loopbackAddress(){return default(InetAddress);}
        public global::java.lang.String  LocalHostName { get; private set;}
    }
}
