//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class InetAddress : global::java.lang.Object, global::java.io.Serializable
    {
        public InetAddress(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public static InetAddress[] getAllByName(global::java.lang.String prm1){return default(InetAddress[]);}
        public static InetAddress getByAddress(global::java.lang.String prm1, byte[] prm2){return default(InetAddress);}
        public static InetAddress getByAddress(byte[] prm1){return default(InetAddress);}
        public static InetAddress getByName(global::java.lang.String prm1){return default(InetAddress);}
        public override int hashCode(){return default(int);}
        public virtual bool isReachable(int prm1){return default(bool);}
        public virtual bool isReachable(NetworkInterface prm1, int prm2, int prm3){return default(bool);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public byte[]  Address { get; private set;}
        public global::java.lang.String  CanonicalHostName { get; private set;}
        public global::java.lang.String  HostAddress { get; private set;}
        public global::java.lang.String  HostName { get; private set;}
        public bool  IsAnyLocalAddress { get; private set;}
        public bool  IsLinkLocalAddress { get; private set;}
        public bool  IsLoopbackAddress { get; private set;}
        public bool  IsMCGlobal { get; private set;}
        public bool  IsMCLinkLocal { get; private set;}
        public bool  IsMCNodeLocal { get; private set;}
        public bool  IsMCOrgLocal { get; private set;}
        public bool  IsMCSiteLocal { get; private set;}
        public bool  IsMulticastAddress { get; private set;}
        public bool  IsSiteLocalAddress { get; private set;}
        public InetAddress  LocalHost { get; private set;}
        public InetAddress  LoopbackAddress { get; private set;}
    }
}
