//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class InetSocketAddress : SocketAddress
    {
        public static InetSocketAddress createUnresolved(global::java.lang.String prm1, int prm2){return default(InetSocketAddress);}
        public bool equals(global::System.Object prm1){return default(bool);}
        public int hashCode(){return default(int);}
        public InetSocketAddress(global::java.lang.String prm1, int prm2){}
        public InetSocketAddress(InetAddress prm1, int prm2){}
        public InetSocketAddress(int prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public InetAddress  Address { get; private set;}
        public global::java.lang.String  HostName { get; private set;}
        public global::java.lang.String  HostString { get; private set;}
        public bool  IsUnresolved { get; private set;}
        public int  Port { get; private set;}
    }
}
