//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class InetAddressImplFactory : global::java.lang.Object
    {
        public InetAddressImplFactory(){}
    }
}
