//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class JarURLConnection : URLConnection
    {
        public URLConnection jarFileURLConnection;
        public JarURLConnection(URL prm1) : base(default(URL)){}
        public global::java.util.jar.Attributes  Attributes { get; private set;}
        public global::java.security.cert.Certificate[]  Certificates { get; private set;}
        public global::java.lang.String  EntryName { get; private set;}
        public global::java.util.jar.JarEntry  JarEntry { get; private set;}
        public global::java.util.jar.JarFile  JarFile { get; private set;}
        public URL  JarFileURL { get; private set;}
        public global::java.util.jar.Attributes  MainAttributes { get; private set;}
        public global::java.util.jar.Manifest  Manifest { get; private set;}
    }
}
