//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class NetPermission : global::java.security.BasicPermission
    {
        public NetPermission(global::java.lang.String prm1) : base(default(global::java.lang.String), default(global::java.lang.String)){}
        public NetPermission(global::java.lang.String prm1, global::java.lang.String prm2) : base(default(global::java.lang.String), default(global::java.lang.String)){}
    }
}
