//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class NetUtil : global::java.lang.Object
    {
        public NetUtil(){}
    }
}
