//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class NetworkInterface_1subIFs : global::java.lang.Object, global::java.util.Enumeration<NetworkInterface>
    {
        public NetworkInterface_1subIFs(){}
        public virtual bool hasMoreElements(){return default(bool);}
        public virtual NetworkInterface nextElement(){return default(NetworkInterface);}
    }
}
