//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class NetworkInterface : global::java.lang.Object
    {
        public NetworkInterface(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public static NetworkInterface getByIndex(int prm1){return default(NetworkInterface);}
        public static NetworkInterface getByInetAddress(InetAddress prm1){return default(NetworkInterface);}
        public static NetworkInterface getByName(global::java.lang.String prm1){return default(NetworkInterface);}
        public override int hashCode(){return default(int);}
        public virtual bool supportsMulticast(){return default(bool);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.lang.String  DisplayName { get; private set;}
        public byte[]  HardwareAddress { get; private set;}
        public int  Index { get; private set;}
        public global::java.util.Enumeration<InetAddress>  InetAddresses { get; private set;}
        public global::java.util.List<InterfaceAddress>  InterfaceAddresses { get; private set;}
        public bool  IsLoopback { get; private set;}
        public bool  IsPointToPoint { get; private set;}
        public bool  IsUp { get; private set;}
        public bool  IsVirtual { get; private set;}
        public int  MTU { get; private set;}
        public global::java.lang.String  Name { get; private set;}
        public global::java.util.Enumeration<NetworkInterface>  NetworkInterfaces { get; private set;}
        public NetworkInterface  Parent { get; private set;}
        public global::java.util.Enumeration<NetworkInterface>  SubInterfaces { get; private set;}
    }
}
