//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class Parts : global::java.lang.Object
    {
        public Parts(){}
    }
}
