//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class PlainSocketImpl : AbstractPlainSocketImpl
    {
        public PlainSocketImpl(){}
        protected override void accept(SocketImpl prm1){}
        protected override void bind(InetAddress prm1, int prm2){}
        protected override void close(){}
        protected override void connect(SocketAddress prm1, int prm2){}
        protected override void connect(global::java.lang.String prm1, int prm2){}
        protected override void connect(InetAddress prm1, int prm2){}
        protected override void create(bool prm1){}
        public override global::System.Object getOption(int prm1){return default(global::System.Object);}
        protected override void sendUrgentData(int prm1){}
        public override void setConnectionReset(){}
        public override void setConnectionResetPending(){}
        public override void setOption(int prm1, global::System.Object prm2){}
        protected override void shutdownInput(){}
        protected override void shutdownOutput(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.io.FileDescriptor  FileDescriptor { get; private set;}
        public InetAddress  InetAddress { get; private set;}
        public global::java.io.InputStream  InputStream { get; private set;}
        public bool  IsClosedOrPending { get; private set;}
        public bool  IsConnectionReset { get; private set;}
        public bool  IsConnectionResetPending { get; private set;}
        public int  LocalPort { get; private set;}
        public global::java.io.OutputStream  OutputStream { get; private set;}
        public int  Port { get; private set;}
        public int  Timeout { get; private set;}
    }
}
