//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class SdpSocketImpl : PlainSocketImpl
    {
        public SdpSocketImpl(){}
        protected override void create(bool prm1){}
    }
}
