//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class SocketOutputStream : global::java.io.FileOutputStream
    {
        public SocketOutputStream() : base(default(global::java.io.FileDescriptor)){}
        public override void close(){}
        protected override void finalize(){}
        public override void write(byte[] prm1){}
        public override void write(byte[] prm1, int prm2, int prm3){}
        public override void write(int prm1){}
        public global::java.nio.channels.FileChannel  Channel { get; private set;}
    }
}
