//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface SocketOptions
    {
        global::System.Object getOption(int prm1);
        void setOption(int prm1, global::System.Object prm2);
    }
}
