//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class SocketPermission : global::java.security.Permission, global::java.io.Serializable
    {
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public override bool implies(global::java.security.Permission prm1){return default(bool);}
        public SocketPermission(global::java.lang.String prm1, global::java.lang.String prm2) : base(default(global::java.lang.String)){}
        public override global::java.security.PermissionCollection newPermissionCollection(){return default(global::java.security.PermissionCollection);}
        public global::java.lang.String  Actions { get; private set;}
    }
}
