//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface SocketOption<T>
    {
        global::java.lang.String name();
        global::java.lang.Class<T> type();
    }
}
