//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class SocketException : global::java.io.IOException
    {
        public SocketException(global::java.lang.String prm1){}
        public SocketException(){}
    }
}
