//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class SocketInputStream : global::java.io.FileInputStream
    {
        public SocketInputStream() : base(default(global::java.io.File)){}
        public override int available(){return default(int);}
        public override void close(){}
        protected override void finalize(){}
        public override int read(){return default(int);}
        public override int read(byte[] prm1){return default(int);}
        public override int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public override long skip(long prm1){return default(long);}
        public global::java.nio.channels.FileChannel  Channel { get; private set;}
    }
}
