//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class Socket : global::java.lang.Object, global::java.io.Closeable
    {
        public virtual void bind(SocketAddress prm1){}
        public virtual void close(){}
        public virtual void connect(SocketAddress prm1){}
        public virtual void connect(SocketAddress prm1, int prm2){}
        public Socket(global::java.lang.String prm1, int prm2, InetAddress prm3, int prm4){}
        public Socket(InetAddress prm1, int prm2, InetAddress prm3, int prm4){}
        public Socket(global::java.lang.String prm1, int prm2, bool prm3){}
        public Socket(InetAddress prm1, int prm2, bool prm3){}
        public Socket(){}
        public Socket(global::java.net.Proxy prm1){}
        public Socket(SocketImpl prm1){}
        public Socket(global::java.lang.String prm1, int prm2){}
        public Socket(InetAddress prm1, int prm2){}
        public virtual void sendUrgentData(int prm1){}
        public virtual void setKeepAlive(bool prm1){}
        public virtual void setOOBInline(bool prm1){}
        public virtual void setPerformancePreferences(int prm1, int prm2, int prm3){}
        public virtual void setReceiveBufferSize(int prm1){}
        public virtual void setReuseAddress(bool prm1){}
        public virtual void setSendBufferSize(int prm1){}
        public static void setSocketImplFactory(SocketImplFactory prm1){}
        public virtual void setSoLinger(bool prm1, int prm2){}
        public virtual void setSoTimeout(int prm1){}
        public virtual void setTcpNoDelay(bool prm1){}
        public virtual void setTrafficClass(int prm1){}
        public virtual void shutdownInput(){}
        public virtual void shutdownOutput(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.nio.channels.SocketChannel  Channel { get; private set;}
        public InetAddress  InetAddress { get; private set;}
        public global::java.io.InputStream  InputStream { get; private set;}
        public bool  IsBound { get; private set;}
        public bool  IsClosed { get; private set;}
        public bool  IsConnected { get; private set;}
        public bool  IsInputShutdown { get; private set;}
        public bool  IsOutputShutdown { get; private set;}
        public bool  KeepAlive { get; set;}
        public InetAddress  LocalAddress { get; private set;}
        public int  LocalPort { get; private set;}
        public SocketAddress  LocalSocketAddress { get; private set;}
        public bool  OOBInline { get; set;}
        public global::java.io.OutputStream  OutputStream { get; private set;}
        public int  Port { get; private set;}
        public int  ReceiveBufferSize { get; set;}
        public SocketAddress  RemoteSocketAddress { get; private set;}
        public bool  ReuseAddress { get; set;}
        public int  SendBufferSize { get; set;}
        public int  SoLinger { get; private set;}
        public int  SoTimeout { get; set;}
        public bool  TcpNoDelay { get; set;}
        public int  TrafficClass { get; set;}
    }
}
