//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class SocketAddress : global::java.lang.Object, global::java.io.Serializable
    {
        public SocketAddress(){}
    }
}
