//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class TwoStacksPlainSocketImpl : AbstractPlainSocketImpl
    {
        protected override void bind(InetAddress prm1, int prm2){}
        protected override void close(){}
        protected override void create(bool prm1){}
        public override global::System.Object getOption(int prm1){return default(global::System.Object);}
        public TwoStacksPlainSocketImpl(bool prm1){}
        public TwoStacksPlainSocketImpl(global::java.io.FileDescriptor prm1, bool prm2){}
        public bool  IsClosedOrPending { get; private set;}
    }
}
