//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class UnknownServiceException : global::java.io.IOException
    {
        public UnknownServiceException(){}
        public UnknownServiceException(global::java.lang.String prm1){}
    }
}
