//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    internal partial class UnknownContentHandler : ContentHandler
    {
        public UnknownContentHandler(){}
        public override global::System.Object getContent(URLConnection prm1){return default(global::System.Object);}
    }
}
