//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class URISyntaxException : global::java.lang.Exception
    {
        public URISyntaxException(global::java.lang.String prm1, global::java.lang.String prm2, int prm3){}
        public URISyntaxException(global::java.lang.String prm1, global::java.lang.String prm2){}
        public int  Index { get; private set;}
        public global::java.lang.String  Input { get; private set;}
        public global::java.lang.String  Message { get; private set;}
        public global::java.lang.String  Reason { get; private set;}
    }
}
