//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class URLClassLoader : global::java.security.SecureClassLoader, global::java.io.Closeable
    {
        protected virtual void addURL(URL prm1){}
        public virtual void close(){}
        protected virtual global::java.lang.Package definePackage(global::java.lang.String prm1, global::java.util.jar.Manifest prm2, URL prm3){return default(global::java.lang.Package);}
        protected override global::java.lang.Class<global::System.Object> findClass(global::java.lang.String prm1){return default(global::java.lang.Class<global::System.Object>);}
        public virtual new URL findResource(global::java.lang.String prm1){return default(URL);}
        public virtual new global::java.util.Enumeration<URL> findResources(global::java.lang.String prm1){return default(global::java.util.Enumeration<URL>);}
        protected override global::java.security.PermissionCollection getPermissions(global::java.security.CodeSource prm1){return default(global::java.security.PermissionCollection);}
        public override global::java.io.InputStream getResourceAsStream(global::java.lang.String prm1){return default(global::java.io.InputStream);}
        public URLClassLoader(URL[] prm1, global::java.lang.ClassLoader prm2, URLStreamHandlerFactory prm3){}
        public URLClassLoader(URL[] prm1){}
        public URLClassLoader(URL[] prm1, global::java.lang.ClassLoader prm2){}
        public static URLClassLoader newInstance(URL[] prm1){return default(URLClassLoader);}
        public static URLClassLoader newInstance(URL[] prm1, global::java.lang.ClassLoader prm2){return default(URLClassLoader);}
        public URL[]  URLs { get; private set;}
    }
}
