//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class URLConnection : global::java.lang.Object
    {
        public bool allowUserInteraction;
        public bool connected;
        public bool doInput;
        public bool doOutput;
        public long ifModifiedSince;
        public URL url;
        public bool useCaches;
        public virtual void addRequestProperty(global::java.lang.String prm1, global::java.lang.String prm2){}
        public virtual void connect(){}
        public virtual global::System.Object getContent(global::java.lang.Class<global::java.lang.Q>[] prm1){return default(global::System.Object);}
        public static global::java.lang.String getDefaultRequestProperty(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getHeaderField(int prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getHeaderField(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual long getHeaderFieldDate(global::java.lang.String prm1, long prm2){return default(long);}
        public virtual int getHeaderFieldInt(global::java.lang.String prm1, int prm2){return default(int);}
        public virtual global::java.lang.String getHeaderFieldKey(int prm1){return default(global::java.lang.String);}
        public virtual long getHeaderFieldLong(global::java.lang.String prm1, long prm2){return default(long);}
        public virtual global::java.lang.String getRequestProperty(global::java.lang.String prm1){return default(global::java.lang.String);}
        public static global::java.lang.String guessContentTypeFromName(global::java.lang.String prm1){return default(global::java.lang.String);}
        public static global::java.lang.String guessContentTypeFromStream(global::java.io.InputStream prm1){return default(global::java.lang.String);}
        public URLConnection(URL prm1){}
        public virtual void setAllowUserInteraction(bool prm1){}
        public virtual void setConnectTimeout(int prm1){}
        public static void setContentHandlerFactory(ContentHandlerFactory prm1){}
        public static void setDefaultAllowUserInteraction(bool prm1){}
        public static void setDefaultRequestProperty(global::java.lang.String prm1, global::java.lang.String prm2){}
        public virtual void setDefaultUseCaches(bool prm1){}
        public virtual void setDoInput(bool prm1){}
        public virtual void setDoOutput(bool prm1){}
        public static void setFileNameMap(FileNameMap prm1){}
        public virtual void setIfModifiedSince(long prm1){}
        public virtual void setReadTimeout(int prm1){}
        public virtual void setRequestProperty(global::java.lang.String prm1, global::java.lang.String prm2){}
        public virtual void setUseCaches(bool prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public bool  AllowUserInteraction { get; set;}
        public int  ConnectTimeout { get; set;}
        public global::System.Object  Content { get; private set;}
        public global::java.lang.String  ContentEncoding { get; private set;}
        public int  ContentLength { get; private set;}
        public long  ContentLengthLong { get; private set;}
        public global::java.lang.String  ContentType { get; private set;}
        public long  Date { get; private set;}
        public bool  DefaultAllowUserInteraction { get; set;}
        public bool  DefaultUseCaches { get; set;}
        public bool  DoInput { get; set;}
        public bool  DoOutput { get; set;}
        public long  Expiration { get; private set;}
        public FileNameMap  FileNameMap { get; set;}
        public global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>>  HeaderFields { get; private set;}
        public long  IfModifiedSince { get; set;}
        public global::java.io.InputStream  InputStream { get; private set;}
        public long  LastModified { get; private set;}
        public global::java.io.OutputStream  OutputStream { get; private set;}
        public global::java.security.Permission  Permission { get; private set;}
        public int  ReadTimeout { get; set;}
        public global::java.util.Map<global::java.lang.String,global::java.util.List<global::java.lang.String>>  RequestProperties { get; private set;}
        public URL  URL { get; private set;}
        public bool  UseCaches { get; set;}
    }
}
