//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial class URLDecoder : global::java.lang.Object
    {
        public static global::java.lang.String decode(global::java.lang.String prm1){return default(global::java.lang.String);}
        public static global::java.lang.String decode(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        public URLDecoder(){}
    }
}
