//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public abstract partial class URLStreamHandler : global::java.lang.Object
    {
        protected virtual bool equals(URL prm1, URL prm2){return default(bool);}
        protected virtual InetAddress getHostAddress(URL prm1){return default(InetAddress);}
        protected virtual int hashCode(URL prm1){return default(int);}
        protected virtual bool hostsEqual(URL prm1, URL prm2){return default(bool);}
        public URLStreamHandler(){}
        protected virtual URLConnection openConnection(URL prm1){return default(URLConnection);}
        protected virtual URLConnection openConnection(URL prm1, global::java.net.Proxy prm2){return default(URLConnection);}
        protected virtual void parseURL(URL prm1, global::java.lang.String prm2, int prm3, int prm4){}
        protected virtual bool sameFile(URL prm1, URL prm2){return default(bool);}
        protected virtual void setURL(URL prm1, global::java.lang.String prm2, global::java.lang.String prm3, int prm4, global::java.lang.String prm5, global::java.lang.String prm6, global::java.lang.String prm7, global::java.lang.String prm8, global::java.lang.String prm9){}
        protected virtual void setURL(URL prm1, global::java.lang.String prm2, global::java.lang.String prm3, int prm4, global::java.lang.String prm5, global::java.lang.String prm6){}
        protected virtual global::java.lang.String toExternalForm(URL prm1){return default(global::java.lang.String);}
        public int  DefaultPort { get; private set;}
    }
}
