//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.net
{
    public partial interface URLStreamHandlerFactory
    {
        URLStreamHandler createURLStreamHandler(global::java.lang.String prm1);
    }
}
