//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.charset
{
    public abstract partial class CharsetEncoder : global::java.lang.Object
    {
        public float averageBytesPerChar(){return default(float);}
        public virtual bool canEncode(global::java.lang.CharSequence prm1){return default(bool);}
        public virtual bool canEncode(char prm1){return default(bool);}
        public Charset charset(){return default(Charset);}
        public ByteBuffer encode(CharBuffer prm1){return default(ByteBuffer);}
        public CoderResult encode(CharBuffer prm1, ByteBuffer prm2, bool prm3){return default(CoderResult);}
        protected virtual CoderResult encodeLoop(CharBuffer prm1, ByteBuffer prm2){return default(CoderResult);}
        public CoderResult flush(ByteBuffer prm1){return default(CoderResult);}
        protected virtual CoderResult implFlush(ByteBuffer prm1){return default(CoderResult);}
        protected virtual void implOnMalformedInput(CodingErrorAction prm1){}
        protected virtual void implOnUnmappableCharacter(CodingErrorAction prm1){}
        protected virtual void implReplaceWith(byte[] prm1){}
        protected virtual void implReset(){}
        public virtual bool isLegalReplacement(byte[] prm1){return default(bool);}
        public CharsetEncoder(Charset prm1, float prm2, float prm3, byte[] prm4){}
        public CharsetEncoder(Charset prm1, float prm2, float prm3){}
        public virtual CodingErrorAction malformedInputAction(){return default(CodingErrorAction);}
        public float maxBytesPerChar(){return default(float);}
        public CharsetEncoder onMalformedInput(CodingErrorAction prm1){return default(CharsetEncoder);}
        public CharsetEncoder onUnmappableCharacter(CodingErrorAction prm1){return default(CharsetEncoder);}
        public byte[] replacement(){return default(byte[]);}
        public CharsetEncoder replaceWith(byte[] prm1){return default(CharsetEncoder);}
        public CharsetEncoder reset(){return default(CharsetEncoder);}
        public virtual CodingErrorAction unmappableCharacterAction(){return default(CodingErrorAction);}
    }
}
