//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.charset
{
    public partial class CoderResult : global::java.lang.Object
    {
        public static CoderResult OVERFLOW;
        public static CoderResult UNDERFLOW;
        public CoderResult(){}
        public virtual int length(){return default(int);}
        public static CoderResult malformedForLength(int prm1){return default(CoderResult);}
        public virtual void throwException(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public static CoderResult unmappableForLength(int prm1){return default(CoderResult);}
        public bool  IsError { get; private set;}
        public bool  IsMalformed { get; private set;}
        public bool  IsOverflow { get; private set;}
        public bool  IsUnderflow { get; private set;}
        public bool  IsUnmappable { get; private set;}
    }
}
