//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.charset
{
    public partial class CodingErrorAction : global::java.lang.Object
    {
        public static CodingErrorAction IGNORE;
        public static CodingErrorAction REPLACE;
        public static CodingErrorAction REPORT;
        public CodingErrorAction(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
