//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace sun.reflect
{
    public partial interface ConstructorAccessor
    {
        global::System.Object newInstance(global::System.Object[] prm1);
    }
}
