//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace sun.reflect
{
    public partial interface MethodAccessor
    {
        global::System.Object invoke(global::System.Object prm1, global::System.Object[] prm2);
    }
}
