//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class AbstractMethodError : IncompatibleClassChangeError
    {
        public AbstractMethodError(){}
        public AbstractMethodError(String prm1){}
    }
}
