//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class ApplicationShutdownHooks : Object
    {
        public ApplicationShutdownHooks(){}
    }
}
