//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ArithmeticException : RuntimeException
    {
        public ArithmeticException(){}
        public ArithmeticException(String prm1){}
    }
}
