//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ArrayStoreException : RuntimeException
    {
        public ArrayStoreException(){}
        public ArrayStoreException(String prm1){}
    }
}
