//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ArrayIndexOutOfBoundsException : IndexOutOfBoundsException
    {
        public ArrayIndexOutOfBoundsException(){}
        public ArrayIndexOutOfBoundsException(int prm1){}
        public ArrayIndexOutOfBoundsException(String prm1){}
    }
}
