//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial interface AutoCloseable
    {
        void close();
    }
}
