//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Boolean : Object, global::java.io.Serializable, Comparable<Boolean>
    {
        public static Boolean FALSE;
        public static Boolean TRUE;
        public static Class<Boolean> TYPE;
        public virtual bool booleanValue(){return default(bool);}
        public static int compare(bool prm1, bool prm2){return default(int);}
        public virtual int compareTo(Boolean prm1){return default(int);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public static bool getBoolean(String prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public Boolean(bool prm1){}
        public Boolean(String prm1){}
        public static bool parseBoolean(String prm1){return default(bool);}
        public static String toString(bool prm1){return default(String);}
        public override String toString(){return default(String);}
        public static Boolean valueOf(String prm1){return default(Boolean);}
        public static Boolean valueOf(bool prm1){return default(Boolean);}
    }
}
