//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class BootstrapMethodError : LinkageError
    {
        public BootstrapMethodError(Throwable prm1){}
        public BootstrapMethodError(String prm1, Throwable prm2){}
        public BootstrapMethodError(String prm1){}
        public BootstrapMethodError(){}
    }
}
