//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class CharacterData02 : CharacterData
    {
        public CharacterData02(){}
    }
}
