//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial interface CharSequence
    {
        char charAt(int prm1);
        int length();
        CharSequence subSequence(int prm1, int prm2);
        String toString();
    }
}
