//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class CharacterData0E : CharacterData
    {
        public CharacterData0E(){}
    }
}
