//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class CharacterData00 : CharacterData
    {
        public CharacterData00(){}
    }
}
