//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class CharacterDataUndefined : CharacterData
    {
        public CharacterDataUndefined(){}
    }
}
