//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class CharacterName : Object
    {
        public CharacterName(){}
        public static String get(int prm1){return default(String);}
    }
}
