//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ClassNotFoundException : ReflectiveOperationException
    {
        public ClassNotFoundException(String prm1, Throwable prm2){}
        public ClassNotFoundException(String prm1){}
        public ClassNotFoundException(){}
        public Throwable  Cause { get; private set;}
        public Throwable  Exception { get; private set;}
    }
}
