//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class CloneNotSupportedException : Exception
    {
        public CloneNotSupportedException(){}
        public CloneNotSupportedException(String prm1){}
    }
}
