//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Compiler : Object
    {
        public Compiler(){}
        public static global::System.Object command(global::System.Object prm1){return default(global::System.Object);}
        public static bool compileClass(Class<global::System.Object> prm1){return default(bool);}
        public static bool compileClasses(String prm1){return default(bool);}
        public static void disable(){}
        public static void enable(){}
    }
}
