//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class EnumConstantNotPresentException : RuntimeException
    {
        public virtual String constantName(){return default(String);}
        public virtual Class<Enum<Q>> enumType(){return default(Class<Enum<Q>>);}
        public EnumConstantNotPresentException(Class<Enum<Q>> prm1, String prm2){}
    }
}
