//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Error : Throwable
    {
        public Error(String prm1, Throwable prm2, bool prm3, bool prm4){}
        public Error(Throwable prm1){}
        public Error(String prm1, Throwable prm2){}
        public Error(String prm1){}
        public Error(){}
    }
}
