//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Exception : Throwable
    {
        public Exception(String prm1, Throwable prm2, bool prm3, bool prm4){}
        public Exception(Throwable prm1){}
        public Exception(String prm1, Throwable prm2){}
        public Exception(String prm1){}
        public Exception(){}
    }
}
