//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ExceptionInInitializerError : LinkageError
    {
        public ExceptionInInitializerError(String prm1){}
        public ExceptionInInitializerError(Throwable prm1){}
        public ExceptionInInitializerError(){}
        public Throwable  Cause { get; private set;}
        public Throwable  Exception { get; private set;}
    }
}
