//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Float : Number, Comparable<Float>
    {
        public static int MAX_EXPONENT;
        public static float MAX_VALUE;
        public static int MIN_EXPONENT;
        public static float MIN_NORMAL;
        public static float MIN_VALUE;
        public static float NaN;
        public static float NEGATIVE_INFINITY;
        public static float POSITIVE_INFINITY;
        public static int SIZE;
        public static Class<Float> TYPE;
        public override byte byteValue(){return default(byte);}
        public static int compare(float prm1, float prm2){return default(int);}
        public virtual int compareTo(Float prm1){return default(int);}
        public override double doubleValue(){return default(double);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public static int floatToIntBits(float prm1){return default(int);}
        public static int floatToRawIntBits(float prm1){return default(int);}
        public override float floatValue(){return default(float);}
        public override int hashCode(){return default(int);}
        public static float intBitsToFloat(int prm1){return default(float);}
        public override int intValue(){return default(int);}
        public static bool isInfinite(float prm1){return default(bool);}
        public static bool isNaN(float prm1){return default(bool);}
        public Float(String prm1){}
        public Float(double prm1){}
        public Float(float prm1){}
        public override long longValue(){return default(long);}
        public static float parseFloat(String prm1){return default(float);}
        public override short shortValue(){return default(short);}
        public static String toHexString(float prm1){return default(String);}
        public static String toString(float prm1){return default(String);}
        public override String toString(){return default(String);}
        public static Float valueOf(float prm1){return default(Float);}
        public static Float valueOf(String prm1){return default(Float);}
        public bool  IsInfinite { get; private set;}
        public bool  IsNaN { get; private set;}
    }
}
