//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IllegalMonitorStateException : RuntimeException
    {
        public IllegalMonitorStateException(){}
        public IllegalMonitorStateException(String prm1){}
    }
}
