//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IllegalThreadStateException : IllegalArgumentException
    {
        public IllegalThreadStateException(){}
        public IllegalThreadStateException(String prm1){}
    }
}
