//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IllegalAccessError : IncompatibleClassChangeError
    {
        public IllegalAccessError(){}
        public IllegalAccessError(String prm1){}
    }
}
