//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IllegalArgumentException : RuntimeException
    {
        public IllegalArgumentException(Throwable prm1){}
        public IllegalArgumentException(String prm1, Throwable prm2){}
        public IllegalArgumentException(String prm1){}
        public IllegalArgumentException(){}
    }
}
