//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IllegalStateException : RuntimeException
    {
        public IllegalStateException(Throwable prm1){}
        public IllegalStateException(String prm1, Throwable prm2){}
        public IllegalStateException(String prm1){}
        public IllegalStateException(){}
    }
}
