//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IncompatibleClassChangeError : LinkageError
    {
        public IncompatibleClassChangeError(){}
        public IncompatibleClassChangeError(String prm1){}
    }
}
