//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class IndexOutOfBoundsException : RuntimeException
    {
        public IndexOutOfBoundsException(){}
        public IndexOutOfBoundsException(String prm1){}
    }
}
