//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class InheritableThreadLocal<T> : ThreadLocal<T>
    {
        protected virtual T childValue(T prm1){return default(T);}
        public InheritableThreadLocal(){}
    }
}
