//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class InterruptedException : Exception
    {
        public InterruptedException(){}
        public InterruptedException(String prm1){}
    }
}
