//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class InternalError : VirtualMachineError
    {
        public InternalError(){}
        public InternalError(String prm1){}
    }
}
