//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial interface Iterable<T> : global::System.Collections.Generic.IEnumerable<T>
    {
        global::java.util.Iterator<T> iterator();
    }
}
