//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Long : Number, Comparable<Long>
    {
        public static long MAX_VALUE;
        public static long MIN_VALUE;
        public static int SIZE;
        public static Class<Long> TYPE;
        public static int bitCount(long prm1){return default(int);}
        public override byte byteValue(){return default(byte);}
        public static int compare(long prm1, long prm2){return default(int);}
        public virtual int compareTo(Long prm1){return default(int);}
        public static Long decode(String prm1){return default(Long);}
        public override double doubleValue(){return default(double);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override float floatValue(){return default(float);}
        public static Long getLong(String prm1){return default(Long);}
        public static Long getLong(String prm1, Long prm2){return default(Long);}
        public static Long getLong(String prm1, long prm2){return default(Long);}
        public override int hashCode(){return default(int);}
        public static long highestOneBit(long prm1){return default(long);}
        public override int intValue(){return default(int);}
        public Long(long prm1){}
        public Long(String prm1){}
        public override long longValue(){return default(long);}
        public static long lowestOneBit(long prm1){return default(long);}
        public static int numberOfLeadingZeros(long prm1){return default(int);}
        public static int numberOfTrailingZeros(long prm1){return default(int);}
        public static long parseLong(String prm1, int prm2){return default(long);}
        public static long parseLong(String prm1){return default(long);}
        public static long reverse(long prm1){return default(long);}
        public static long reverseBytes(long prm1){return default(long);}
        public static long rotateLeft(long prm1, int prm2){return default(long);}
        public static long rotateRight(long prm1, int prm2){return default(long);}
        public override short shortValue(){return default(short);}
        public static int signum(long prm1){return default(int);}
        public static String toBinaryString(long prm1){return default(String);}
        public static String toHexString(long prm1){return default(String);}
        public static String toOctalString(long prm1){return default(String);}
        public static String toString(long prm1, int prm2){return default(String);}
        public override String toString(){return default(String);}
        public static String toString(long prm1){return default(String);}
        public static Long valueOf(long prm1){return default(Long);}
        public static Long valueOf(String prm1, int prm2){return default(Long);}
        public static Long valueOf(String prm1){return default(Long);}
    }
}
