//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class NegativeArraySizeException : RuntimeException
    {
        public NegativeArraySizeException(){}
        public NegativeArraySizeException(String prm1){}
    }
}
