//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class NoSuchFieldError : IncompatibleClassChangeError
    {
        public NoSuchFieldError(){}
        public NoSuchFieldError(String prm1){}
    }
}
