//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class NullPointerException : RuntimeException
    {
        public NullPointerException(){}
        public NullPointerException(String prm1){}
    }
}
