//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Object
    {
        protected virtual global::System.Object clone(){return default(global::System.Object);}
        public virtual bool equals(global::System.Object prm1){return default(bool);}
        protected virtual void finalize(){}
        public virtual int hashCode(){return default(int);}
        public Object(){}
        public void notify(){}
        public void notifyAll(){}
        public virtual String toString(){return default(String);}
        public void wait(long prm1, int prm2){}
        public void wait(long prm1){}
        public void wait(){}
        public Class<global::System.Object>  Class { get; private set;}
    }
}
