//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class OutOfMemoryError : VirtualMachineError
    {
        public OutOfMemoryError(){}
        public OutOfMemoryError(String prm1){}
    }
}
