//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial interface Override : global::java.lang.annotation.Annotation
    {
    }
}
