//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class Package_1PackageInfoProxy : Object
    {
        public Package_1PackageInfoProxy(){}
    }
}
