//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    internal partial class ProcessImpl : Process
    {
        public ProcessImpl(){}
        public override void destroy(){}
        public override int exitValue(){return default(int);}
        public virtual new void finalize(){}
        public override int waitFor(){return default(int);}
        public global::java.io.InputStream  ErrorStream { get; private set;}
        public global::java.io.InputStream  InputStream { get; private set;}
        public global::java.io.OutputStream  OutputStream { get; private set;}
    }
}
