//***************************************************
//* This file was generated by JSharp
//***************************************************
using java.util;
namespace java.lang
{
    internal partial class ProcessEnvironment : global::java.util.HashMap<String,String>
    {
        public ProcessEnvironment(){}
        public override bool containsKey(global::System.Object prm1){return default(bool);}
        public override bool containsValue(global::System.Object prm1){return default(bool);}
        public override global::java.util.Set<Map_Entry<String,String>> entrySet(){return default(global::java.util.Set<Map_Entry<String,String>>);}
        public override String get(global::System.Object prm1){return default(String);}
        public override global::java.util.Set<String> keySet(){return default(global::java.util.Set<String>);}
        public override String put(String prm1, String prm2){return default(String);}
        public override String remove(global::System.Object prm1){return default(String);}
        public override global::java.util.Collection<String> values(){return default(global::java.util.Collection<String>);}
    }
}
