//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial interface Readable
    {
        int read(global::java.nio.CharBuffer prm1);
    }
}
