//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ReflectiveOperationException : Exception
    {
        public ReflectiveOperationException(Throwable prm1){}
        public ReflectiveOperationException(String prm1, Throwable prm2){}
        public ReflectiveOperationException(String prm1){}
        public ReflectiveOperationException(){}
    }
}
