//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Runtime : Object
    {
        public Runtime(){}
        public virtual void addShutdownHook(Thread prm1){}
        public virtual int availableProcessors(){return default(int);}
        public virtual Process exec(String[] prm1){return default(Process);}
        public virtual Process exec(String prm1, String[] prm2, global::java.io.File prm3){return default(Process);}
        public virtual Process exec(String[] prm1, String[] prm2, global::java.io.File prm3){return default(Process);}
        public virtual Process exec(String prm1, String[] prm2){return default(Process);}
        public virtual Process exec(String prm1){return default(Process);}
        public virtual Process exec(String[] prm1, String[] prm2){return default(Process);}
        public virtual void exit(int prm1){}
        public virtual long freeMemory(){return default(long);}
        public virtual void gc(){}
        public virtual global::java.io.InputStream getLocalizedInputStream(global::java.io.InputStream prm1){return default(global::java.io.InputStream);}
        public virtual global::java.io.OutputStream getLocalizedOutputStream(global::java.io.OutputStream prm1){return default(global::java.io.OutputStream);}
        public virtual void halt(int prm1){}
        public virtual void load(String prm1){}
        public virtual void loadLibrary(String prm1){}
        public virtual long maxMemory(){return default(long);}
        public virtual bool removeShutdownHook(Thread prm1){return default(bool);}
        public virtual void runFinalization(){}
        public static void runFinalizersOnExit(bool prm1){}
        public virtual long totalMemory(){return default(long);}
        public virtual void traceInstructions(bool prm1){}
        public virtual void traceMethodCalls(bool prm1){}
        public Runtime  Runtime___ { get; private set;}
    }
}
