//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class RuntimeException : Exception
    {
        public RuntimeException(String prm1, Throwable prm2, bool prm3, bool prm4){}
        public RuntimeException(Throwable prm1){}
        public RuntimeException(String prm1, Throwable prm2){}
        public RuntimeException(String prm1){}
        public RuntimeException(){}
    }
}
