//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class SecurityException : RuntimeException
    {
        public SecurityException(Throwable prm1){}
        public SecurityException(String prm1, Throwable prm2){}
        public SecurityException(String prm1){}
        public SecurityException(){}
    }
}
