//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class SecurityManager : Object
    {
        public bool inCheck;
        public virtual void checkAccept(String prm1, int prm2){}
        public virtual void checkAccess(ThreadGroup prm1){}
        public virtual void checkAccess(Thread prm1){}
        public virtual void checkAwtEventQueueAccess(){}
        public virtual void checkConnect(String prm1, int prm2){}
        public virtual void checkConnect(String prm1, int prm2, global::System.Object prm3){}
        public virtual void checkCreateClassLoader(){}
        public virtual void checkDelete(String prm1){}
        public virtual void checkExec(String prm1){}
        public virtual void checkExit(int prm1){}
        public virtual void checkLink(String prm1){}
        public virtual void checkListen(int prm1){}
        public virtual void checkMemberAccess(Class<global::System.Object> prm1, int prm2){}
        public virtual void checkMulticast(global::java.net.InetAddress prm1, byte prm2){}
        public virtual void checkMulticast(global::java.net.InetAddress prm1){}
        public virtual void checkPackageAccess(String prm1){}
        public virtual void checkPackageDefinition(String prm1){}
        public virtual void checkPermission(global::java.security.Permission prm1, global::System.Object prm2){}
        public virtual void checkPermission(global::java.security.Permission prm1){}
        public virtual void checkPrintJobAccess(){}
        public virtual void checkPropertiesAccess(){}
        public virtual void checkPropertyAccess(String prm1){}
        public virtual void checkRead(String prm1){}
        public virtual void checkRead(String prm1, global::System.Object prm2){}
        public virtual void checkRead(global::java.io.FileDescriptor prm1){}
        public virtual void checkSecurityAccess(String prm1){}
        public virtual void checkSetFactory(){}
        public virtual void checkSystemClipboardAccess(){}
        public virtual bool checkTopLevelWindow(global::System.Object prm1){return default(bool);}
        public virtual void checkWrite(global::java.io.FileDescriptor prm1){}
        public virtual void checkWrite(String prm1){}
        protected virtual int classDepth(String prm1){return default(int);}
        protected virtual int classLoaderDepth(){return default(int);}
        protected virtual ClassLoader currentClassLoader(){return default(ClassLoader);}
        protected virtual Class<global::System.Object> currentLoadedClass(){return default(Class<global::System.Object>);}
        protected virtual bool inClass(String prm1){return default(bool);}
        protected virtual bool inClassLoader(){return default(bool);}
        public SecurityManager(){}
        public Class<Q>[]  ClassContext { get; private set;}
        public bool  InCheck { get; private set;}
        public global::System.Object  SecurityContext { get; private set;}
        public ThreadGroup  ThreadGroup { get; private set;}
    }
}
