//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Short : Number, Comparable<Short>
    {
        public static short MAX_VALUE;
        public static short MIN_VALUE;
        public static int SIZE;
        public static Class<Short> TYPE;
        public override byte byteValue(){return default(byte);}
        public static int compare(short prm1, short prm2){return default(int);}
        public virtual int compareTo(Short prm1){return default(int);}
        public static Short decode(String prm1){return default(Short);}
        public override double doubleValue(){return default(double);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override float floatValue(){return default(float);}
        public override int hashCode(){return default(int);}
        public override int intValue(){return default(int);}
        public Short(short prm1){}
        public Short(String prm1){}
        public override long longValue(){return default(long);}
        public static short parseShort(String prm1, int prm2){return default(short);}
        public static short parseShort(String prm1){return default(short);}
        public static short reverseBytes(short prm1){return default(short);}
        public override short shortValue(){return default(short);}
        public override String toString(){return default(String);}
        public static String toString(short prm1){return default(String);}
        public static Short valueOf(String prm1, int prm2){return default(Short);}
        public static Short valueOf(String prm1){return default(Short);}
        public static Short valueOf(short prm1){return default(Short);}
    }
}
