//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class StackOverflowError : VirtualMachineError
    {
        public StackOverflowError(){}
        public StackOverflowError(String prm1){}
    }
}
