//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class StackTraceElement : Object, global::java.io.Serializable
    {
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public StackTraceElement(String prm1, String prm2, String prm3, int prm4){}
        public override String toString(){return default(String);}
        public String  ClassName { get; private set;}
        public String  FileName { get; private set;}
        public bool  IsNativeMethod { get; private set;}
        public int  LineNumber { get; private set;}
        public String  MethodName { get; private set;}
    }
}
