//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class StringBuilder : AbstractStringBuilder, global::java.io.Serializable, CharSequence
    {
        public virtual StringBuilder append(char[] prm1){return default(StringBuilder);}
        public virtual StringBuilder append(char[] prm1, int prm2, int prm3){return default(StringBuilder);}
        public virtual StringBuilder append(bool prm1){return default(StringBuilder);}
        public virtual StringBuilder append(StringBuffer prm1){return default(StringBuilder);}
        public virtual StringBuilder append(CharSequence prm1){return default(StringBuilder);}
        public virtual StringBuilder append(CharSequence prm1, int prm2, int prm3){return default(StringBuilder);}
        public virtual StringBuilder append(float prm1){return default(StringBuilder);}
        public virtual StringBuilder append(String prm1){return default(StringBuilder);}
        public virtual StringBuilder append(global::System.Object prm1){return default(StringBuilder);}
        public virtual StringBuilder append(double prm1){return default(StringBuilder);}
        public virtual StringBuilder append(char prm1){return default(StringBuilder);}
        public virtual StringBuilder append(int prm1){return default(StringBuilder);}
        public virtual StringBuilder append(long prm1){return default(StringBuilder);}
        public virtual StringBuilder appendCodePoint(int prm1){return default(StringBuilder);}
        public virtual StringBuilder delete(int prm1, int prm2){return default(StringBuilder);}
        public virtual StringBuilder deleteCharAt(int prm1){return default(StringBuilder);}
        public override int indexOf(String prm1, int prm2){return default(int);}
        public override int indexOf(String prm1){return default(int);}
        public virtual StringBuilder insert(int prm1, float prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, long prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, int prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, global::System.Object prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, char[] prm2, int prm3, int prm4){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, double prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, CharSequence prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, char[] prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, CharSequence prm2, int prm3, int prm4){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, String prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, bool prm2){return default(StringBuilder);}
        public virtual StringBuilder insert(int prm1, char prm2){return default(StringBuilder);}
        public StringBuilder(CharSequence prm1){}
        public StringBuilder(String prm1){}
        public StringBuilder(int prm1){}
        public StringBuilder(){}
        public override int lastIndexOf(String prm1){return default(int);}
        public override int lastIndexOf(String prm1, int prm2){return default(int);}
        public virtual StringBuilder replace(int prm1, int prm2, String prm3){return default(StringBuilder);}
        public virtual StringBuilder reverse(){return default(StringBuilder);}
        public override String toString(){return default(String);}
    }
}
