//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class System : Object
    {
        public static global::java.io.PrintStream err;
        public static global::java.io.InputStream @in;
        public static global::java.io.PrintStream @out;
        public System(){}
        public static void arraycopy(global::System.Object prm1, int prm2, global::System.Object prm3, int prm4, int prm5){}
        public static String clearProperty(String prm1){return default(String);}
        public static global::java.io.Console console(){return default(global::java.io.Console);}
        public static long currentTimeMillis(){return default(long);}
        public static void exit(int prm1){}
        public static void gc(){}
        public static global::java.util.Map<String,String> getenv(){return default(global::java.util.Map<String,String>);}
        public static String getenv(String prm1){return default(String);}
        public static String getProperty(String prm1){return default(String);}
        public static String getProperty(String prm1, String prm2){return default(String);}
        public static int identityHashCode(global::System.Object prm1){return default(int);}
        public static global::java.nio.channels.Channel inheritedChannel(){return default(global::java.nio.channels.Channel);}
        public static String lineSeparator(){return default(String);}
        public static void load(String prm1){}
        public static void loadLibrary(String prm1){}
        public static String mapLibraryName(String prm1){return default(String);}
        public static long nanoTime(){return default(long);}
        public static void runFinalization(){}
        public static void runFinalizersOnExit(bool prm1){}
        public static void setErr(global::java.io.PrintStream prm1){}
        public static void setIn(global::java.io.InputStream prm1){}
        public static void setOut(global::java.io.PrintStream prm1){}
        public static void setProperties(global::java.util.Properties prm1){}
        public static String setProperty(String prm1, String prm2){return default(String);}
        public static void setSecurityManager(SecurityManager prm1){}
        public global::java.util.Properties  Properties { get; set;}
        public SecurityManager  SecurityManager { get; set;}
    }
}
