//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class ThreadLocal<T> : Object
    {
        public virtual T get(){return default(T);}
        protected virtual T initialValue(){return default(T);}
        public ThreadLocal(){}
        public virtual void remove(){}
        public virtual void set(T prm1){}
    }
}
