//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Throwable : global::System.Exception, global::java.io.Serializable
    {
        public void addSuppressed(Throwable prm1){}
        public virtual Throwable fillInStackTrace(){return default(Throwable);}
        public virtual Throwable initCause(Throwable prm1){return default(Throwable);}
        public Throwable(String prm1, Throwable prm2, bool prm3, bool prm4){}
        public Throwable(Throwable prm1){}
        public Throwable(String prm1, Throwable prm2){}
        public Throwable(String prm1){}
        public Throwable(){}
        public virtual void printStackTrace(global::java.io.PrintWriter prm1){}
        public virtual void printStackTrace(){}
        public virtual void printStackTrace(global::java.io.PrintStream prm1){}
        public virtual void setStackTrace(StackTraceElement[] prm1){}
        public virtual String toString(){return default(String);}
        public Throwable  Cause { get; private set;}
        public String  LocalizedMessage { get; private set;}
        public String  Message { get; private set;}
        public StackTraceElement[]  StackTrace { get; set;}
        public Throwable[]  Suppressed { get; private set;}
    }
}
