//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class TypeNotPresentException : RuntimeException
    {
        public TypeNotPresentException(String prm1, Throwable prm2){}
        public virtual String typeName(){return default(String);}
    }
}
