//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class UnknownError : VirtualMachineError
    {
        public UnknownError(){}
        public UnknownError(String prm1){}
    }
}
