//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class UnsatisfiedLinkError : LinkageError
    {
        public UnsatisfiedLinkError(){}
        public UnsatisfiedLinkError(String prm1){}
    }
}
