//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class UnsupportedOperationException : RuntimeException
    {
        public UnsupportedOperationException(Throwable prm1){}
        public UnsupportedOperationException(String prm1, Throwable prm2){}
        public UnsupportedOperationException(String prm1){}
        public UnsupportedOperationException(){}
    }
}
