//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang
{
    public partial class Void : Object
    {
        public static Class<Void> TYPE;
        public Void(){}
    }
}
