//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.math
{
    internal partial class BitSieve : global::java.lang.Object
    {
        public BitSieve(){}
    }
}
