//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.math
{
    public partial class MathContext : global::java.lang.Object, global::java.io.Serializable
    {
        public static MathContext DECIMAL128;
        public static MathContext DECIMAL32;
        public static MathContext DECIMAL64;
        public static MathContext UNLIMITED;
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public MathContext(global::java.lang.String prm1){}
        public MathContext(int prm1, RoundingMode prm2){}
        public MathContext(int prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public int  Precision { get; private set;}
        public RoundingMode  RoundingMode { get; private set;}
    }
}
