//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.math
{
    internal partial class MutableBigInteger : global::java.lang.Object
    {
        public MutableBigInteger(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
