//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.math
{
    internal partial class SignedMutableBigInteger : MutableBigInteger
    {
        public SignedMutableBigInteger(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
