//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public partial interface Channel : global::java.io.Closeable
    {
        void close();
        bool  IsOpen { get;}
    }
}
