//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class DatagramChannel : global::java.nio.channels.spi.AbstractSelectableChannel, ByteChannel, ScatteringByteChannel, GatheringByteChannel, MulticastChannel
    {
        public virtual DatagramChannel bind(global::java.net.SocketAddress prm1){return default(DatagramChannel);}
        NetworkChannel NetworkChannel.bind(global::java.net.SocketAddress prm1){return default(NetworkChannel);}
        public virtual DatagramChannel connect(global::java.net.SocketAddress prm1){return default(DatagramChannel);}
        public virtual DatagramChannel disconnect(){return default(DatagramChannel);}
        public virtual T getOption<T>(global::java.net.SocketOption<T> prm1){return default(T);}
        public DatagramChannel(global::java.nio.channels.spi.SelectorProvider prm1) : base(default(global::java.nio.channels.spi.SelectorProvider)){}
        public virtual MembershipKey join(global::java.net.InetAddress prm1, global::java.net.NetworkInterface prm2){return default(MembershipKey);}
        public virtual MembershipKey join(global::java.net.InetAddress prm1, global::java.net.NetworkInterface prm2, global::java.net.InetAddress prm3){return default(MembershipKey);}
        public static DatagramChannel open(global::java.net.ProtocolFamily prm1){return default(DatagramChannel);}
        public static DatagramChannel open(){return default(DatagramChannel);}
        public virtual long read(ByteBuffer[] prm1, int prm2, int prm3){return default(long);}
        public virtual int read(ByteBuffer prm1){return default(int);}
        public long read(ByteBuffer[] prm1){return default(long);}
        public virtual global::java.net.SocketAddress receive(ByteBuffer prm1){return default(global::java.net.SocketAddress);}
        public virtual int send(ByteBuffer prm1, global::java.net.SocketAddress prm2){return default(int);}
        public virtual DatagramChannel setOption<T>(global::java.net.SocketOption<T> prm1, T prm2){return default(DatagramChannel);}
        NetworkChannel NetworkChannel.setOption<T>(global::java.net.SocketOption<T> prm1, T prm2){return default(NetworkChannel);}
        public virtual global::java.net.DatagramSocket socket(){return default(global::java.net.DatagramSocket);}
        public virtual global::java.util.Set<global::java.net.SocketOption<global::System.Object>> supportedOptions(){return default(global::java.util.Set<global::java.net.SocketOption<global::System.Object>>);}
        public int validOps(){return default(int);}
        public long write(ByteBuffer[] prm1){return default(long);}
        public virtual long write(ByteBuffer[] prm1, int prm2, int prm3){return default(long);}
        public virtual int write(ByteBuffer prm1){return default(int);}
        public bool  IsConnected { get; private set;}
        public global::java.net.SocketAddress  LocalAddress { get; private set;}
        public global::java.net.SocketAddress  RemoteAddress { get; private set;}
    }
}
