//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class FileLock : global::java.lang.Object, global::java.lang.AutoCloseable
    {
        public virtual Channel acquiredBy(){return default(Channel);}
        public FileChannel channel(){return default(FileChannel);}
        public void close(){}
        public FileLock(FileChannel prm1, long prm2, long prm3, bool prm4){}
        public FileLock(AsynchronousFileChannel prm1, long prm2, long prm3, bool prm4){}
        public bool overlaps(long prm1, long prm2){return default(bool);}
        public long position(){return default(long);}
        public virtual void release(){}
        public long size(){return default(long);}
        public global::java.lang.String toString(){return default(global::java.lang.String);}
        public bool  IsShared { get; private set;}
        public bool  IsValid { get; private set;}
    }
}
