//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public partial interface GatheringByteChannel : WritableByteChannel
    {
        long write(ByteBuffer[] prm1, int prm2, int prm3);
        long write(ByteBuffer[] prm1);
    }
}
