//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public partial interface InterruptibleChannel : Channel
    {
    }
}
