//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class MembershipKey : global::java.lang.Object
    {
        public virtual MembershipKey block(global::java.net.InetAddress prm1){return default(MembershipKey);}
        public virtual MulticastChannel channel(){return default(MulticastChannel);}
        public virtual void drop(){}
        public virtual global::java.net.InetAddress group(){return default(global::java.net.InetAddress);}
        public MembershipKey(){}
        public virtual global::java.net.NetworkInterface networkInterface(){return default(global::java.net.NetworkInterface);}
        public virtual global::java.net.InetAddress sourceAddress(){return default(global::java.net.InetAddress);}
        public virtual MembershipKey unblock(global::java.net.InetAddress prm1){return default(MembershipKey);}
        public bool  IsValid { get; private set;}
    }
}
