//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public partial interface NetworkChannel : Channel
    {
        NetworkChannel bind(global::java.net.SocketAddress prm1);
        T getOption<T>(global::java.net.SocketOption<T> prm1);
        NetworkChannel setOption<T>(global::java.net.SocketOption<T> prm1, T prm2);
        global::java.util.Set<global::java.net.SocketOption<global::System.Object>> supportedOptions();
        global::java.net.SocketAddress  LocalAddress { get;}
    }
}
