//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class Pipe : global::java.lang.Object
    {
        public abstract partial class SinkChannel : global::java.nio.channels.spi.AbstractSelectableChannel, global::java.nio.channels.WritableByteChannel, global::java.nio.channels.GatheringByteChannel
        {
            public SinkChannel(global::java.nio.channels.spi.SelectorProvider prm1) : base(default(global::java.nio.channels.spi.SelectorProvider)){}
            public int validOps(){return default(int);}
            public virtual int write(global::java.nio.ByteBuffer prm1){return default(int);}
            public virtual long write(global::java.nio.ByteBuffer[] prm1, int prm2, int prm3){return default(long);}
            public virtual long write(global::java.nio.ByteBuffer[] prm1){return default(long);}
        }
        public abstract partial class SourceChannel : global::java.nio.channels.spi.AbstractSelectableChannel, global::java.nio.channels.ReadableByteChannel, global::java.nio.channels.ScatteringByteChannel
        {
            public SourceChannel(global::java.nio.channels.spi.SelectorProvider prm1) : base(default(global::java.nio.channels.spi.SelectorProvider)){}
            public virtual int read(global::java.nio.ByteBuffer prm1){return default(int);}
            public virtual long read(global::java.nio.ByteBuffer[] prm1, int prm2, int prm3){return default(long);}
            public virtual long read(global::java.nio.ByteBuffer[] prm1){return default(long);}
            public int validOps(){return default(int);}
        }
        public Pipe(){}
        public static Pipe open(){return default(Pipe);}
        public virtual Pipe.SinkChannel sink(){return default(Pipe.SinkChannel);}
        public virtual Pipe.SourceChannel source(){return default(Pipe.SourceChannel);}
    }
}
