//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class SelectionKey : global::java.lang.Object
    {
        public static int OP_ACCEPT;
        public static int OP_CONNECT;
        public static int OP_READ;
        public static int OP_WRITE;
        public global::System.Object attach(global::System.Object prm1){return default(global::System.Object);}
        public global::System.Object attachment(){return default(global::System.Object);}
        public virtual void cancel(){}
        public virtual SelectableChannel channel(){return default(SelectableChannel);}
        public virtual int interestOps(){return default(int);}
        public virtual SelectionKey interestOps(int prm1){return default(SelectionKey);}
        public SelectionKey(){}
        public virtual int readyOps(){return default(int);}
        public virtual Selector selector(){return default(Selector);}
        public bool  IsAcceptable { get; private set;}
        public bool  IsConnectable { get; private set;}
        public bool  IsReadable { get; private set;}
        public bool  IsValid { get; private set;}
        public bool  IsWritable { get; private set;}
    }
}
