//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public abstract partial class ServerSocketChannel : global::java.nio.channels.spi.AbstractSelectableChannel, NetworkChannel
    {
        public virtual SocketChannel accept(){return default(SocketChannel);}
        public virtual ServerSocketChannel bind(global::java.net.SocketAddress prm1, int prm2){return default(ServerSocketChannel);}
        public ServerSocketChannel bind(global::java.net.SocketAddress prm1){return default(ServerSocketChannel);}
        NetworkChannel NetworkChannel.bind(global::java.net.SocketAddress prm1){return default(NetworkChannel);}
        public virtual T getOption<T>(global::java.net.SocketOption<T> prm1){return default(T);}
        public ServerSocketChannel(global::java.nio.channels.spi.SelectorProvider prm1) : base(default(global::java.nio.channels.spi.SelectorProvider)){}
        public static ServerSocketChannel open(){return default(ServerSocketChannel);}
        public virtual ServerSocketChannel setOption<T>(global::java.net.SocketOption<T> prm1, T prm2){return default(ServerSocketChannel);}
        NetworkChannel NetworkChannel.setOption<T>(global::java.net.SocketOption<T> prm1, T prm2){return default(NetworkChannel);}
        public virtual global::java.net.ServerSocket socket(){return default(global::java.net.ServerSocket);}
        public virtual global::java.util.Set<global::java.net.SocketOption<global::System.Object>> supportedOptions(){return default(global::java.util.Set<global::java.net.SocketOption<global::System.Object>>);}
        public int validOps(){return default(int);}
        public global::java.net.SocketAddress  LocalAddress { get; private set;}
    }
}
