//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels
{
    public partial interface WritableByteChannel : Channel
    {
        int write(ByteBuffer prm1);
    }
}
