//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class AbstractCollection<E> : global::java.lang.Object, Collection<E>
    {
        public virtual bool add(E prm1){return default(bool);}
        public virtual bool addAll(Collection<E> prm1){return default(bool);}
        public virtual void clear(){}
        public virtual bool contains(global::System.Object prm1){return default(bool);}
        public virtual bool containsAll(Collection<global::System.Object> prm1){return default(bool);}
        public virtual Iterator<E> iterator(){return default(Iterator<E>);}
        public AbstractCollection(){}
        public virtual bool remove(global::System.Object prm1){return default(bool);}
        public virtual bool removeAll(Collection<global::System.Object> prm1){return default(bool);}
        public virtual bool retainAll(Collection<global::System.Object> prm1){return default(bool);}
        public virtual int size(){return default(int);}
        public virtual T[] toArray<T>(T[] prm1){return default(T[]);}
        public virtual global::System.Object[] toArray(){return default(global::System.Object[]);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public bool  IsEmpty { get; private set;}
    }
}
