//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class AbstractSequentialList<E> : AbstractList<E>
    {
        public override void add(int prm1, E prm2){}
        public override bool addAll(int prm1, Collection<E> prm2){return default(bool);}
        public override E get(int prm1){return default(E);}
        public override Iterator<E> iterator(){return default(Iterator<E>);}
        public AbstractSequentialList(){}
        public override ListIterator<E> listIterator(int prm1){return default(ListIterator<E>);}
        public override E remove(int prm1){return default(E);}
        public override E set(int prm1, E prm2){return default(E);}
    }
}
