//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class AbstractQueue<E> : AbstractCollection<E>, Queue<E>
    {
        public override bool add(E prm1){return default(bool);}
        public override bool addAll(Collection<E> prm1){return default(bool);}
        public override void clear(){}
        public virtual E element(){return default(E);}
        public AbstractQueue(){}
        public virtual bool offer(E prm1){return default(bool);}
        public virtual E peek(){return default(E);}
        public virtual E poll(){return default(E);}
        public virtual E remove(){return default(E);}
    }
}
