//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class ComparableTimSort : global::java.lang.Object
    {
        public ComparableTimSort(){}
    }
}
