//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface Comparator<T>
    {
        int compare(T prm1, T prm2);
        bool equals(global::System.Object prm1);
    }
}
