//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class ConcurrentModificationException : global::java.lang.RuntimeException
    {
        public ConcurrentModificationException(global::java.lang.String prm1, global::java.lang.Throwable prm2){}
        public ConcurrentModificationException(global::java.lang.Throwable prm1){}
        public ConcurrentModificationException(global::java.lang.String prm1){}
        public ConcurrentModificationException(){}
    }
}
