//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Date : global::java.lang.Object, global::java.io.Serializable, global::java.lang.Cloneable, global::java.lang.Comparable<Date>
    {
        public virtual bool after(Date prm1){return default(bool);}
        public virtual bool before(Date prm1){return default(bool);}
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public virtual int compareTo(Date prm1){return default(int);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public Date(global::java.lang.String prm1){}
        public Date(int prm1, int prm2, int prm3, int prm4, int prm5, int prm6){}
        public Date(int prm1, int prm2, int prm3, int prm4, int prm5){}
        public Date(){}
        public Date(long prm1){}
        public Date(int prm1, int prm2, int prm3){}
        public static long parse(global::java.lang.String prm1){return default(long);}
        public virtual void setDate(int prm1){}
        public virtual void setHours(int prm1){}
        public virtual void setMinutes(int prm1){}
        public virtual void setMonth(int prm1){}
        public virtual void setSeconds(int prm1){}
        public virtual void setTime(long prm1){}
        public virtual void setYear(int prm1){}
        public virtual global::java.lang.String toGMTString(){return default(global::java.lang.String);}
        public virtual global::java.lang.String toLocaleString(){return default(global::java.lang.String);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public static long UTC(int prm1, int prm2, int prm3, int prm4, int prm5, int prm6){return default(long);}
        public int  Date___ { get; set;}
        public int  Day { get; private set;}
        public int  Hours { get; set;}
        public int  Minutes { get; set;}
        public int  Month { get; set;}
        public int  Seconds { get; set;}
        public long  Time { get; set;}
        public int  TimezoneOffset { get; private set;}
        public int  Year { get; set;}
    }
}
