//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class Dictionary<K,V> : global::java.lang.Object
    {
        public virtual Enumeration<V> elements(){return default(Enumeration<V>);}
        public virtual V get(global::System.Object prm1){return default(V);}
        public Dictionary(){}
        public virtual Enumeration<K> keys(){return default(Enumeration<K>);}
        public virtual V put(K prm1, V prm2){return default(V);}
        public virtual V remove(global::System.Object prm1){return default(V);}
        public virtual int size(){return default(int);}
        public bool  IsEmpty { get; private set;}
    }
}
