//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface Enumeration<E>
    {
        bool hasMoreElements();
        E nextElement();
    }
}
