//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class EventListenerProxy<T> : global::java.lang.Object, EventListener
    {
        public EventListenerProxy(T prm1){}
        public T  Listener { get; private set;}
    }
}
