//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Formatter : global::java.lang.Object, global::java.io.Closeable, global::java.io.Flushable
    {
        public partial class BigDecimalLayoutForm : global::java.lang.Enum<global::java.util.Formatter.BigDecimalLayoutForm>
        {
            public static global::java.util.Formatter.BigDecimalLayoutForm DECIMAL_FLOAT;
            public static global::java.util.Formatter.BigDecimalLayoutForm SCIENTIFIC;
            public BigDecimalLayoutForm(){}
            public static global::java.util.Formatter.BigDecimalLayoutForm valueOf(global::java.lang.String prm1){return default(global::java.util.Formatter.BigDecimalLayoutForm);}
            public static global::java.util.Formatter.BigDecimalLayoutForm[] values(){return default(global::java.util.Formatter.BigDecimalLayoutForm[]);}
        }
        public virtual void close(){}
        public virtual void flush(){}
        public virtual Formatter format(global::java.lang.String prm1, global::System.Object[] prm2){return default(Formatter);}
        public virtual Formatter format(Locale prm1, global::java.lang.String prm2, global::System.Object[] prm3){return default(Formatter);}
        public virtual global::java.io.IOException ioException(){return default(global::java.io.IOException);}
        public Formatter(global::java.io.File prm1, global::java.lang.String prm2){}
        public Formatter(global::java.io.File prm1){}
        public Formatter(global::java.lang.String prm1, global::java.lang.String prm2, Locale prm3){}
        public Formatter(global::java.lang.String prm1, global::java.lang.String prm2){}
        public Formatter(global::java.lang.String prm1){}
        public Formatter(global::java.io.OutputStream prm1, global::java.lang.String prm2){}
        public Formatter(global::java.io.OutputStream prm1){}
        public Formatter(global::java.io.PrintStream prm1){}
        public Formatter(global::java.io.File prm1, global::java.lang.String prm2, Locale prm3){}
        public Formatter(){}
        public Formatter(global::java.io.OutputStream prm1, global::java.lang.String prm2, Locale prm3){}
        public Formatter(global::java.lang.Appendable prm1, Locale prm2){}
        public Formatter(Locale prm1){}
        public Formatter(global::java.lang.Appendable prm1){}
        public virtual Locale locale(){return default(Locale);}
        public virtual global::java.lang.Appendable @out(){return default(global::java.lang.Appendable);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
