//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class GregorianCalendar : Calendar
    {
        public static int AD;
        public static int BC;
        public override void add(int prm1, int prm2){}
        public override global::System.Object clone(){return default(global::System.Object);}
        protected override void computeFields(){}
        protected override void computeTime(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int getActualMaximum(int prm1){return default(int);}
        public override int getActualMinimum(int prm1){return default(int);}
        public override int getGreatestMinimum(int prm1){return default(int);}
        public override int getLeastMaximum(int prm1){return default(int);}
        public override int getMaximum(int prm1){return default(int);}
        public override int getMinimum(int prm1){return default(int);}
        public override int hashCode(){return default(int);}
        public virtual bool isLeapYear(int prm1){return default(bool);}
        public GregorianCalendar(int prm1, int prm2, int prm3){}
        public GregorianCalendar(int prm1, int prm2, int prm3, int prm4, int prm5){}
        public GregorianCalendar(int prm1, int prm2, int prm3, int prm4, int prm5, int prm6){}
        public GregorianCalendar(){}
        public GregorianCalendar(TimeZone prm1){}
        public GregorianCalendar(Locale prm1){}
        public GregorianCalendar(TimeZone prm1, Locale prm2){}
        public override void roll(int prm1, bool prm2){}
        public override void roll(int prm1, int prm2){}
        public virtual void setGregorianChange(Date prm1){}
        public override void setTimeZone(TimeZone prm1){}
        public override void setWeekDate(int prm1, int prm2, int prm3){}
        public Date  GregorianChange { get; set;}
        public bool  IsWeekDateSupported { get; private set;}
        public TimeZone  TimeZone { get; set;}
        public int  WeeksInWeekYear { get; private set;}
        public int  WeekYear { get; private set;}
    }
}
