//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class HashSet<E> : AbstractSet<E>, Set<E>, global::java.lang.Cloneable, global::java.io.Serializable
    {
        public override bool add(E prm1){return default(bool);}
        public override void clear(){}
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public override bool contains(global::System.Object prm1){return default(bool);}
        public override Iterator<E> iterator(){return default(Iterator<E>);}
        public HashSet(int prm1){}
        public HashSet(int prm1, float prm2){}
        public HashSet(Collection<E> prm1){}
        public HashSet(){}
        public override bool remove(global::System.Object prm1){return default(bool);}
        public override int size(){return default(int);}
        public bool  IsEmpty { get; private set;}
    }
}
