//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class HashMap<K,V> : AbstractMap<K,V>, Map<K,V>, global::java.lang.Cloneable, global::java.io.Serializable
    {
        public override void clear(){}
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public override bool containsKey(global::System.Object prm1){return default(bool);}
        public override bool containsValue(global::System.Object prm1){return default(bool);}
        public override Set<Map_Entry<K,V>> entrySet(){return default(Set<Map_Entry<K,V>>);}
        public override V get(global::System.Object prm1){return default(V);}
        public HashMap(Map<K,V> prm1){}
        public HashMap(){}
        public HashMap(int prm1){}
        public HashMap(int prm1, float prm2){}
        public override Set<K> keySet(){return default(Set<K>);}
        public override V put(K prm1, V prm2){return default(V);}
        public override void putAll(Map<K,V> prm1){}
        public override V remove(global::System.Object prm1){return default(V);}
        public override int size(){return default(int);}
        public override Collection<V> values(){return default(Collection<V>);}
        public bool  IsEmpty { get; private set;}
    }
}
