//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Hashtable<K,V> : Dictionary<K,V>, Map<K,V>, global::java.lang.Cloneable, global::java.io.Serializable
    {
        public virtual void clear(){}
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public virtual bool contains(global::System.Object prm1){return default(bool);}
        public virtual bool containsKey(global::System.Object prm1){return default(bool);}
        public virtual bool containsValue(global::System.Object prm1){return default(bool);}
        public override Enumeration<V> elements(){return default(Enumeration<V>);}
        public virtual Set<Map_Entry<K,V>> entrySet(){return default(Set<Map_Entry<K,V>>);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override V get(global::System.Object prm1){return default(V);}
        public override int hashCode(){return default(int);}
        public Hashtable(){}
        public Hashtable(int prm1){}
        public Hashtable(int prm1, float prm2){}
        public Hashtable(Map<K,V> prm1){}
        public override Enumeration<K> keys(){return default(Enumeration<K>);}
        public virtual Set<K> keySet(){return default(Set<K>);}
        public override V put(K prm1, V prm2){return default(V);}
        public virtual void putAll(Map<K,V> prm1){}
        protected virtual void rehash(){}
        public override V remove(global::System.Object prm1){return default(V);}
        public override int size(){return default(int);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public virtual Collection<V> values(){return default(Collection<V>);}
        public bool  IsEmpty { get; private set;}
    }
}
