//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class IllegalFormatCodePointException : IllegalFormatException
    {
        public IllegalFormatCodePointException(int prm1){}
        public int  CodePoint { get; private set;}
        public global::java.lang.String  Message { get; private set;}
    }
}
