//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class IllegalFormatWidthException : IllegalFormatException
    {
        public IllegalFormatWidthException(int prm1){}
        public global::java.lang.String  Message { get; private set;}
        public int  Width { get; private set;}
    }
}
