//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class IllegalFormatException : global::java.lang.IllegalArgumentException
    {
        public IllegalFormatException(){}
    }
}
