//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class IllformedLocaleException : global::java.lang.RuntimeException
    {
        public IllformedLocaleException(global::java.lang.String prm1, int prm2){}
        public IllformedLocaleException(global::java.lang.String prm1){}
        public IllformedLocaleException(){}
        public int  ErrorIndex { get; private set;}
    }
}
