//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class InputMismatchException : NoSuchElementException
    {
        public InputMismatchException(){}
        public InputMismatchException(global::java.lang.String prm1){}
    }
}
