//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface Iterator<E>
    {
        bool hasNext();
        E next();
        void remove();
    }
}
