//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class JapaneseImperialCalendar : Calendar
    {
        public static int BEFORE_MEIJI;
        public static int HEISEI;
        public static int MEIJI;
        public static int SHOWA;
        public static int TAISHO;
        public override void add(int prm1, int prm2){}
        public override global::System.Object clone(){return default(global::System.Object);}
        protected override void computeFields(){}
        protected override void computeTime(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int getActualMaximum(int prm1){return default(int);}
        public override int getActualMinimum(int prm1){return default(int);}
        public override global::java.lang.String getDisplayName(int prm1, int prm2, Locale prm3){return default(global::java.lang.String);}
        public override Map<global::java.lang.String,global::java.lang.Integer> getDisplayNames(int prm1, int prm2, Locale prm3){return default(Map<global::java.lang.String,global::java.lang.Integer>);}
        public override int getGreatestMinimum(int prm1){return default(int);}
        public override int getLeastMaximum(int prm1){return default(int);}
        public override int getMaximum(int prm1){return default(int);}
        public override int getMinimum(int prm1){return default(int);}
        public override int hashCode(){return default(int);}
        public JapaneseImperialCalendar(TimeZone prm1, Locale prm2){}
        public override void roll(int prm1, bool prm2){}
        public override void roll(int prm1, int prm2){}
        public override void setTimeZone(TimeZone prm1){}
        public TimeZone  TimeZone { get; set;}
    }
}
