//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class JumboEnumSet<E> : EnumSet<E>
    {
        public JumboEnumSet(){}
        public override bool add(E prm1){return default(bool);}
        public override bool addAll(Collection<E> prm1){return default(bool);}
        public override void clear(){}
        public override EnumSet<E> clone(){return default(EnumSet<E>);}
        public override bool contains(global::System.Object prm1){return default(bool);}
        public override bool containsAll(Collection<global::System.Object> prm1){return default(bool);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override Iterator<E> iterator(){return default(Iterator<E>);}
        public override bool remove(global::System.Object prm1){return default(bool);}
        public override bool removeAll(Collection<global::System.Object> prm1){return default(bool);}
        public override bool retainAll(Collection<global::System.Object> prm1){return default(bool);}
        public override int size(){return default(int);}
        public bool  IsEmpty { get; private set;}
    }
}
