//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class LinkedHashMap<K,V> : HashMap<K,V>, Map<K,V>
    {
        public override void clear(){}
        public override bool containsValue(global::System.Object prm1){return default(bool);}
        public override V get(global::System.Object prm1){return default(V);}
        public LinkedHashMap(int prm1, float prm2, bool prm3){}
        public LinkedHashMap(Map<K,V> prm1){}
        public LinkedHashMap(){}
        public LinkedHashMap(int prm1){}
        public LinkedHashMap(int prm1, float prm2){}
        protected virtual bool removeEldestEntry(Map_Entry<K,V> prm1){return default(bool);}
    }
}
