//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface ListIterator<E> : Iterator<E>
    {
        void add(E prm1);
        bool hasPrevious();
        int nextIndex();
        E previous();
        int previousIndex();
        void set(E prm1);
    }
}
