//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class ListResourceBundle : ResourceBundle
    {
        public global::System.Object handleGetObject(global::java.lang.String prm1){return default(global::System.Object);}
        protected override Set<global::java.lang.String> handleKeySet(){return default(Set<global::java.lang.String>);}
        public ListResourceBundle(){}
        public global::System.Object[][]  Contents { get; private set;}
        public Enumeration<global::java.lang.String>  Keys { get; private set;}
    }
}
