//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class LocaleISOData : global::java.lang.Object
    {
        public LocaleISOData(){}
    }
}
