//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Locale : global::java.lang.Object, global::java.lang.Cloneable, global::java.io.Serializable
    {
        public partial class Builder : global::java.lang.Object
        {
            public virtual global::java.util.Locale.Builder addUnicodeLocaleAttribute(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale build(){return default(global::java.util.Locale);}
            public virtual global::java.util.Locale.Builder clear(){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder clearExtensions(){return default(global::java.util.Locale.Builder);}
            public Builder(){}
            public virtual global::java.util.Locale.Builder removeUnicodeLocaleAttribute(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setExtension(char prm1, global::java.lang.String prm2){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setLanguage(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setLanguageTag(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setLocale(global::java.util.Locale prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setRegion(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setScript(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setUnicodeLocaleKeyword(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.util.Locale.Builder);}
            public virtual global::java.util.Locale.Builder setVariant(global::java.lang.String prm1){return default(global::java.util.Locale.Builder);}
        }
        public partial class Category : global::java.lang.Enum<global::java.util.Locale.Category>
        {
            public static global::java.util.Locale.Category DISPLAY;
            public static global::java.util.Locale.Category FORMAT;
            public Category(){}
            public static global::java.util.Locale.Category valueOf(global::java.lang.String prm1){return default(global::java.util.Locale.Category);}
            public static global::java.util.Locale.Category[] values(){return default(global::java.util.Locale.Category[]);}
        }
        public static Locale CANADA;
        public static Locale CANADA_FRENCH;
        public static Locale CHINA;
        public static Locale CHINESE;
        public static Locale ENGLISH;
        public static Locale FRANCE;
        public static Locale FRENCH;
        public static Locale GERMAN;
        public static Locale GERMANY;
        public static Locale ITALIAN;
        public static Locale ITALY;
        public static Locale JAPAN;
        public static Locale JAPANESE;
        public static Locale KOREA;
        public static Locale KOREAN;
        public static Locale PRC;
        public static char PRIVATE_USE_EXTENSION;
        public static Locale ROOT;
        public static Locale SIMPLIFIED_CHINESE;
        public static Locale TAIWAN;
        public static Locale TRADITIONAL_CHINESE;
        public static Locale UK;
        public static char UNICODE_LOCALE_EXTENSION;
        public static Locale US;
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public static Locale forLanguageTag(global::java.lang.String prm1){return default(Locale);}
        public static Locale getDefault(Locale.Category prm1){return default(Locale);}
        public virtual global::java.lang.String getDisplayCountry(Locale prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getDisplayLanguage(Locale prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getDisplayName(Locale prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getDisplayScript(Locale prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getDisplayVariant(Locale prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getExtension(char prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getUnicodeLocaleType(global::java.lang.String prm1){return default(global::java.lang.String);}
        public override int hashCode(){return default(int);}
        public Locale(global::java.lang.String prm1){}
        public Locale(global::java.lang.String prm1, global::java.lang.String prm2){}
        public Locale(global::java.lang.String prm1, global::java.lang.String prm2, global::java.lang.String prm3){}
        public static void setDefault(Locale prm1){}
        public static void setDefault(Locale.Category prm1, Locale prm2){}
        public virtual global::java.lang.String toLanguageTag(){return default(global::java.lang.String);}
        public global::java.lang.String toString(){return default(global::java.lang.String);}
        public Locale[]  AvailableLocales { get; private set;}
        public global::java.lang.String  Country { get; private set;}
        public Locale  Default { get; set;}
        public global::java.lang.String  DisplayCountry { get; private set;}
        public global::java.lang.String  DisplayLanguage { get; private set;}
        public global::java.lang.String  DisplayName { get; private set;}
        public global::java.lang.String  DisplayScript { get; private set;}
        public global::java.lang.String  DisplayVariant { get; private set;}
        public Set<global::java.lang.Character>  ExtensionKeys { get; private set;}
        public global::java.lang.String  ISO3Country { get; private set;}
        public global::java.lang.String  ISO3Language { get; private set;}
        public global::java.lang.String[]  ISOCountries { get; private set;}
        public global::java.lang.String[]  ISOLanguages { get; private set;}
        public global::java.lang.String  Language { get; private set;}
        public global::java.lang.String  Script { get; private set;}
        public Set<global::java.lang.String>  UnicodeLocaleAttributes { get; private set;}
        public Set<global::java.lang.String>  UnicodeLocaleKeys { get; private set;}
        public global::java.lang.String  Variant { get; private set;}
    }
}
