//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface Map<K,V>
    {
        void clear();
        bool containsKey(global::System.Object prm1);
        bool containsValue(global::System.Object prm1);
        Set<Map_Entry<K,V>> entrySet();
        bool equals(global::System.Object prm1);
        V get(global::System.Object prm1);
        int hashCode();
        Set<K> keySet();
        V put(K prm1, V prm2);
        void putAll(Map<K,V> prm1);
        V remove(global::System.Object prm1);
        int size();
        Collection<V> values();
        bool  IsEmpty { get;}
    }
}
