//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class MissingFormatArgumentException : IllegalFormatException
    {
        public MissingFormatArgumentException(global::java.lang.String prm1){}
        public global::java.lang.String  FormatSpecifier { get; private set;}
        public global::java.lang.String  Message { get; private set;}
    }
}
