//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface NavigableSet<E> : SortedSet<E>
    {
        E ceiling(E prm1);
        Iterator<E> descendingIterator();
        NavigableSet<E> descendingSet();
        E floor(E prm1);
        NavigableSet<E> headSet(E prm1, bool prm2);
        E higher(E prm1);
        Iterator<E> iterator();
        E lower(E prm1);
        E pollFirst();
        E pollLast();
        NavigableSet<E> subSet(E prm1, bool prm2, E prm3, bool prm4);
        NavigableSet<E> tailSet(E prm1, bool prm2);
    }
}
