//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class NoSuchElementException : global::java.lang.RuntimeException
    {
        public NoSuchElementException(){}
        public NoSuchElementException(global::java.lang.String prm1){}
    }
}
