//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Objects : global::java.lang.Object
    {
        public Objects(){}
        public static int compare<T>(T prm1, T prm2, Comparator<global::System.Object> prm3){return default(int);}
        public static bool deepEquals(global::System.Object prm1, global::System.Object prm2){return default(bool);}
        public static bool equals(global::System.Object prm1, global::System.Object prm2){return default(bool);}
        public static int hash(global::System.Object[] prm1){return default(int);}
        public static int hashCode(global::System.Object prm1){return default(int);}
        public static T requireNonNull<T>(T prm1){return default(T);}
        public static T requireNonNull<T>(T prm1, global::java.lang.String prm2){return default(T);}
        public static global::java.lang.String toString(global::System.Object prm1){return default(global::java.lang.String);}
        public static global::java.lang.String toString(global::System.Object prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
    }
}
