//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface Observer
    {
        void update(Observable prm1, global::System.Object prm2);
    }
}
