//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class PropertyPermissionCollection : global::java.security.PermissionCollection, global::java.io.Serializable
    {
        public override void add(global::java.security.Permission prm1){}
        public virtual Enumeration<global::java.lang.Q> elements(){return default(Enumeration<global::java.lang.Q>);}
        public override bool implies(global::java.security.Permission prm1){return default(bool);}
        public PropertyPermissionCollection(){}
    }
}
