//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Properties : Hashtable<global::System.Object,global::System.Object>
    {
        public Properties defaults;
        public virtual global::java.lang.String getProperty(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String getProperty(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        public Properties(){}
        public Properties(Properties prm1){}
        public virtual void list(global::java.io.PrintWriter prm1){}
        public virtual void list(global::java.io.PrintStream prm1){}
        public virtual void load(global::java.io.Reader prm1){}
        public virtual void load(global::java.io.InputStream prm1){}
        public virtual void loadFromXML(global::java.io.InputStream prm1){}
        public virtual Enumeration<global::System.Object> propertyNames(){return default(Enumeration<global::System.Object>);}
        public virtual void save(global::java.io.OutputStream prm1, global::java.lang.String prm2){}
        public virtual global::System.Object setProperty(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::System.Object);}
        public virtual void store(global::java.io.Writer prm1, global::java.lang.String prm2){}
        public virtual void store(global::java.io.OutputStream prm1, global::java.lang.String prm2){}
        public virtual void storeToXML(global::java.io.OutputStream prm1, global::java.lang.String prm2){}
        public virtual void storeToXML(global::java.io.OutputStream prm1, global::java.lang.String prm2, global::java.lang.String prm3){}
        public virtual Set<global::java.lang.String> stringPropertyNames(){return default(Set<global::java.lang.String>);}
    }
}
