//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Random : global::java.lang.Object, global::java.io.Serializable
    {
        public Random(){}
        public Random(long prm1){}
        protected virtual int next(int prm1){return default(int);}
        public virtual bool nextBoolean(){return default(bool);}
        public virtual void nextBytes(byte[] prm1){}
        public virtual double nextDouble(){return default(double);}
        public virtual float nextFloat(){return default(float);}
        public virtual double nextGaussian(){return default(double);}
        public virtual int nextInt(){return default(int);}
        public virtual int nextInt(int prm1){return default(int);}
        public virtual long nextLong(){return default(long);}
        public virtual void setSeed(long prm1){}
    }
}
