//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class RandomAccessSubList<E> : SubList<E>, RandomAccess
    {
        public RandomAccessSubList(){}
        public override List<E> subList(int prm1, int prm2){return default(List<E>);}
    }
}
