//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class ResourceBundle : global::java.lang.Object
    {
        public partial class Control : global::java.lang.Object
        {
            public static global::java.util.List<global::java.lang.String> FORMAT_CLASS;
            public static global::java.util.List<global::java.lang.String> FORMAT_DEFAULT;
            public static global::java.util.List<global::java.lang.String> FORMAT_PROPERTIES;
            public static long TTL_DONT_CACHE;
            public static long TTL_NO_EXPIRATION_CONTROL;
            public virtual global::java.util.List<global::java.util.Locale> getCandidateLocales(global::java.lang.String prm1, global::java.util.Locale prm2){return default(global::java.util.List<global::java.util.Locale>);}
            public static global::java.util.ResourceBundle.Control getControl(global::java.util.List<global::java.lang.String> prm1){return default(global::java.util.ResourceBundle.Control);}
            public virtual global::java.util.Locale getFallbackLocale(global::java.lang.String prm1, global::java.util.Locale prm2){return default(global::java.util.Locale);}
            public virtual global::java.util.List<global::java.lang.String> getFormats(global::java.lang.String prm1){return default(global::java.util.List<global::java.lang.String>);}
            public static global::java.util.ResourceBundle.Control getNoFallbackControl(global::java.util.List<global::java.lang.String> prm1){return default(global::java.util.ResourceBundle.Control);}
            public virtual long getTimeToLive(global::java.lang.String prm1, global::java.util.Locale prm2){return default(long);}
            public Control(){}
            public virtual bool needsReload(global::java.lang.String prm1, global::java.util.Locale prm2, global::java.lang.String prm3, global::java.lang.ClassLoader prm4, global::java.util.ResourceBundle prm5, long prm6){return default(bool);}
            public virtual global::java.util.ResourceBundle newBundle(global::java.lang.String prm1, global::java.util.Locale prm2, global::java.lang.String prm3, global::java.lang.ClassLoader prm4, bool prm5){return default(global::java.util.ResourceBundle);}
            public virtual global::java.lang.String toBundleName(global::java.lang.String prm1, global::java.util.Locale prm2){return default(global::java.lang.String);}
            public global::java.lang.String toResourceName(global::java.lang.String prm1, global::java.lang.String prm2){return default(global::java.lang.String);}
        }
        public ResourceBundle parent;
        public static void clearCache(global::java.lang.ClassLoader prm1){}
        public static void clearCache(){}
        public virtual bool containsKey(global::java.lang.String prm1){return default(bool);}
        public static ResourceBundle getBundle(global::java.lang.String prm1, Locale prm2, ResourceBundle.Control prm3){return default(ResourceBundle);}
        public static ResourceBundle getBundle(global::java.lang.String prm1, Locale prm2, global::java.lang.ClassLoader prm3){return default(ResourceBundle);}
        public static ResourceBundle getBundle(global::java.lang.String prm1, Locale prm2, global::java.lang.ClassLoader prm3, ResourceBundle.Control prm4){return default(ResourceBundle);}
        public static ResourceBundle getBundle(global::java.lang.String prm1){return default(ResourceBundle);}
        public static ResourceBundle getBundle(global::java.lang.String prm1, ResourceBundle.Control prm2){return default(ResourceBundle);}
        public static ResourceBundle getBundle(global::java.lang.String prm1, Locale prm2){return default(ResourceBundle);}
        public global::System.Object getObject(global::java.lang.String prm1){return default(global::System.Object);}
        public global::java.lang.String getString(global::java.lang.String prm1){return default(global::java.lang.String);}
        public global::java.lang.String[] getStringArray(global::java.lang.String prm1){return default(global::java.lang.String[]);}
        protected virtual global::System.Object handleGetObject(global::java.lang.String prm1){return default(global::System.Object);}
        protected virtual Set<global::java.lang.String> handleKeySet(){return default(Set<global::java.lang.String>);}
        public ResourceBundle(){}
        public virtual Set<global::java.lang.String> keySet(){return default(Set<global::java.lang.String>);}
        protected virtual void setParent(ResourceBundle prm1){}
        public Enumeration<global::java.lang.String>  Keys { get; private set;}
        public Locale  Locale { get; private set;}
    }
}
