//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class ServiceLoader<S> : global::java.lang.Object, global::java.lang.Iterable<S>
    {
        public ServiceLoader(){}
        public virtual Iterator<S> iterator(){return default(Iterator<S>);}
        public static ServiceLoader<S> load<S>(global::java.lang.Class<S> prm1){return default(ServiceLoader<S>);}
        public static ServiceLoader<S> load<S>(global::java.lang.Class<S> prm1, global::java.lang.ClassLoader prm2){return default(ServiceLoader<S>);}
        public static ServiceLoader<S> loadInstalled<S>(global::java.lang.Class<S> prm1){return default(ServiceLoader<S>);}
        public virtual void reload(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
