//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface SortedSet<E> : Set<E>
    {
        Comparator<global::System.Object> comparator();
        E first();
        SortedSet<E> headSet(E prm1);
        E last();
        SortedSet<E> subSet(E prm1, E prm2);
        SortedSet<E> tailSet(E prm1);
    }
}
