//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial interface SortedMap<K,V> : Map<K,V>
    {
        Comparator<global::System.Object> comparator();
        K firstKey();
        SortedMap<K,V> headMap(K prm1);
        K lastKey();
        SortedMap<K,V> subMap(K prm1, K prm2);
        SortedMap<K,V> tailMap(K prm1);
    }
}
