//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class StringTokenizer : global::java.lang.Object, Enumeration<global::System.Object>
    {
        public virtual int countTokens(){return default(int);}
        public virtual bool hasMoreElements(){return default(bool);}
        public virtual bool hasMoreTokens(){return default(bool);}
        public StringTokenizer(global::java.lang.String prm1, global::java.lang.String prm2){}
        public StringTokenizer(global::java.lang.String prm1, global::java.lang.String prm2, bool prm3){}
        public StringTokenizer(global::java.lang.String prm1){}
        public virtual global::System.Object nextElement(){return default(global::System.Object);}
        public virtual global::java.lang.String nextToken(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String nextToken(){return default(global::java.lang.String);}
    }
}
