//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class Timer : global::java.lang.Object
    {
        public virtual void cancel(){}
        public Timer(global::java.lang.String prm1){}
        public Timer(bool prm1){}
        public Timer(){}
        public Timer(global::java.lang.String prm1, bool prm2){}
        public virtual int purge(){return default(int);}
        public virtual void schedule(TimerTask prm1, Date prm2, long prm3){}
        public virtual void schedule(TimerTask prm1, long prm2){}
        public virtual void schedule(TimerTask prm1, Date prm2){}
        public virtual void schedule(TimerTask prm1, long prm2, long prm3){}
        public virtual void scheduleAtFixedRate(TimerTask prm1, long prm2, long prm3){}
        public virtual void scheduleAtFixedRate(TimerTask prm1, Date prm2, long prm3){}
    }
}
