//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class TimerThread : global::java.lang.Thread
    {
        public TimerThread(){}
        public override void run(){}
    }
}
