//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public abstract partial class TimeZone : global::java.lang.Object, global::java.io.Serializable, global::java.lang.Cloneable
    {
        public static int LONG;
        public static int SHORT;
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public static global::java.lang.String[] getAvailableIDs(int prm1){return default(global::java.lang.String[]);}
        public virtual global::java.lang.String getDisplayName(bool prm1, int prm2, Locale prm3){return default(global::java.lang.String);}
        public global::java.lang.String getDisplayName(bool prm1, int prm2){return default(global::java.lang.String);}
        public global::java.lang.String getDisplayName(Locale prm1){return default(global::java.lang.String);}
        public virtual int getOffset(int prm1, int prm2, int prm3, int prm4, int prm5, int prm6){return default(int);}
        public virtual int getOffset(long prm1){return default(int);}
        public static TimeZone getTimeZone(global::java.lang.String prm1){return default(TimeZone);}
        public virtual bool hasSameRules(TimeZone prm1){return default(bool);}
        public virtual bool inDaylightTime(Date prm1){return default(bool);}
        public TimeZone(){}
        public virtual bool observesDaylightTime(){return default(bool);}
        public static void setDefault(TimeZone prm1){}
        public virtual void setID(global::java.lang.String prm1){}
        public virtual void setRawOffset(int prm1){}
        public virtual bool useDaylightTime(){return default(bool);}
        public global::java.lang.String[]  AvailableIDs { get; private set;}
        public TimeZone  Default { get; set;}
        public global::java.lang.String  DisplayName { get; private set;}
        public int  DSTSavings { get; private set;}
        public global::java.lang.String  ID { get; set;}
        public int  RawOffset { get; set;}
    }
}
