//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class TimSort<T> : global::java.lang.Object
    {
        public TimSort(){}
    }
}
