//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class UnknownFormatConversionException : IllegalFormatException
    {
        public UnknownFormatConversionException(global::java.lang.String prm1){}
        public global::java.lang.String  Conversion { get; private set;}
        public global::java.lang.String  Message { get; private set;}
    }
}
