//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    public partial class UnknownFormatFlagsException : IllegalFormatException
    {
        public UnknownFormatFlagsException(global::java.lang.String prm1){}
        public global::java.lang.String  Flags { get; private set;}
        public global::java.lang.String  Message { get; private set;}
    }
}
