//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util
{
    internal partial class XMLUtils : global::java.lang.Object
    {
        public XMLUtils(){}
    }
}
