//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.zip
{
    public partial class Deflater : global::java.lang.Object
    {
        public static int BEST_COMPRESSION;
        public static int BEST_SPEED;
        public static int DEFAULT_COMPRESSION;
        public static int DEFAULT_STRATEGY;
        public static int DEFLATED;
        public static int FILTERED;
        public static int FULL_FLUSH;
        public static int HUFFMAN_ONLY;
        public static int NO_COMPRESSION;
        public static int NO_FLUSH;
        public static int SYNC_FLUSH;
        public virtual int deflate(byte[] prm1, int prm2, int prm3){return default(int);}
        public virtual int deflate(byte[] prm1){return default(int);}
        public virtual int deflate(byte[] prm1, int prm2, int prm3, int prm4){return default(int);}
        public virtual void end(){}
        protected override void finalize(){}
        public virtual void finish(){}
        public virtual bool finished(){return default(bool);}
        public Deflater(){}
        public Deflater(int prm1){}
        public Deflater(int prm1, bool prm2){}
        public virtual bool needsInput(){return default(bool);}
        public virtual void reset(){}
        public virtual void setDictionary(byte[] prm1){}
        public virtual void setDictionary(byte[] prm1, int prm2, int prm3){}
        public virtual void setInput(byte[] prm1){}
        public virtual void setInput(byte[] prm1, int prm2, int prm3){}
        public virtual void setLevel(int prm1){}
        public virtual void setStrategy(int prm1){}
        public int  Adler { get; private set;}
        public long  BytesRead { get; private set;}
        public long  BytesWritten { get; private set;}
        public int  TotalIn { get; private set;}
        public int  TotalOut { get; private set;}
    }
}
