//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.zip
{
    public partial class ZipException : global::java.io.IOException
    {
        public ZipException(){}
        public ZipException(global::java.lang.String prm1){}
    }
}
