//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.zip
{
    public partial class ZipEntry : global::java.lang.Object, ZipConstants, global::java.lang.Cloneable
    {
        public static int DEFLATED;
        public static int STORED;
        public virtual new global::System.Object clone(){return default(global::System.Object);}
        public override int hashCode(){return default(int);}
        public ZipEntry(ZipEntry prm1){}
        public ZipEntry(global::java.lang.String prm1){}
        public virtual void setComment(global::java.lang.String prm1){}
        public virtual void setCompressedSize(long prm1){}
        public virtual void setCrc(long prm1){}
        public virtual void setExtra(byte[] prm1){}
        public virtual void setMethod(int prm1){}
        public virtual void setSize(long prm1){}
        public virtual void setTime(long prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.lang.String  Comment { get; set;}
        public long  CompressedSize { get; set;}
        public long  Crc { get; set;}
        public byte[]  Extra { get; set;}
        public bool  IsDirectory { get; private set;}
        public int  Method { get; set;}
        public global::java.lang.String  Name { get; private set;}
        public long  Size { get; set;}
        public long  Time { get; set;}
    }
}
