//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace sun.security.util
{
    public partial class ManifestEntryVerifier : global::java.lang.Object
    {
        public virtual void setEntry(global::java.lang.String prm1, global::java.util.jar.JarEntry prm2){}
        public ManifestEntryVerifier(global::java.util.jar.Manifest prm1){}
        public virtual void update(byte[] prm1, int prm2, int prm3){}
        public virtual void update(byte prm1){}
        public virtual global::java.security.CodeSigner[] verify(global::java.util.Hashtable<global::java.lang.String,global::java.security.CodeSigner[]> prm1, global::java.util.Hashtable<global::java.lang.String,global::java.security.CodeSigner[]> prm2){return default(global::java.security.CodeSigner[]);}
        public global::java.util.jar.JarEntry  Entry { get; private set;}
    }
}
