//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace sun.nio.ch
{
    public partial interface DirectBuffer
    {
        long address();
        global::System.Object attachment();
        global::sun.misc.Cleaner cleaner();
    }
}
