//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.beans
{
    public partial class PropertyChangeEvent : global::java.util.EventObject
    {
        public PropertyChangeEvent(global::System.Object prm1, global::java.lang.String prm2, global::System.Object prm3, global::System.Object prm4) : base(default(global::System.Object)){}
        public virtual void setPropagationId(global::System.Object prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::System.Object  NewValue { get; private set;}
        public global::System.Object  OldValue { get; private set;}
        public global::System.Object  PropagationId { get; set;}
        public global::java.lang.String  PropertyName { get; private set;}
    }
}
