////***************************************************
////* This file was generated by JSharp
////***************************************************
//namespace java.lang.@ref
//{
//    internal partial class Finalizer : FinalReference<Q>
//    {
//        public Finalizer(){}
//    }
//}
