////***************************************************
////* This file was generated by JSharp
////***************************************************
//namespace java.lang.@ref
//{
//    internal partial class FinalReference<T> : Reference<T>
//    {
//        public FinalReference(T prm1, ReferenceQueue<global::System.Object> prm2){}
//    }
//}
