//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.@ref
{
    public partial class PhantomReference<T> : Reference<T>
    {
        protected PhantomReference() { }
        public override T get(){return default(T);}
        public PhantomReference(T prm1, ReferenceQueue<global::System.Object> prm2){}
    }
}
