//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.@ref
{
    public abstract partial class Reference<T> : Object
    {
        public Reference(){}
        public virtual void clear(){}
        public virtual bool enqueue(){return default(bool);}
        public virtual T get(){return default(T);}
        public bool  IsEnqueued { get; private set;}
    }
}
