//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.@ref
{
    public partial class SoftReference<T> : Reference<T>
    {
        public override T get(){return default(T);}
        public SoftReference(T prm1){}
        public SoftReference(T prm1, ReferenceQueue<global::System.Object> prm2){}
    }
}
