//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.@ref
{
    public partial class WeakReference<T> : Reference<T>
    {
        public WeakReference(T prm1){}
        public WeakReference(T prm1, ReferenceQueue<global::System.Object> prm2){}
    }
}
