//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.jar
{
    public partial class JarException : global::java.util.zip.ZipException
    {
        public JarException(){}
        public JarException(global::java.lang.String prm1){}
    }
}
