//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.jar
{
    public partial class JarInputStream : global::java.util.zip.ZipInputStream
    {
        protected override global::java.util.zip.ZipEntry createZipEntry(global::java.lang.String prm1){return default(global::java.util.zip.ZipEntry);}
        public JarInputStream(global::java.io.InputStream prm1) : base(default(global::java.io.InputStream), default(global::java.nio.charset.Charset)){}
        public JarInputStream(global::java.io.InputStream prm1, bool prm2) : base(default(global::java.io.InputStream), default(global::java.nio.charset.Charset)){}
        public override int read(byte[] prm1, int prm2, int prm3){return default(int);}
        public Manifest  Manifest { get; private set;}
        public global::java.util.zip.ZipEntry  NextEntry { get; private set;}
        public JarEntry  NextJarEntry { get; private set;}
    }
}
