//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security.cert
{
    public abstract partial class CertPath : global::java.lang.Object, global::java.io.Serializable
    {
        protected partial class CertPathRep : global::java.lang.Object, global::java.io.Serializable
        {
            public CertPathRep(global::java.lang.String prm1, byte[] prm2){}
            protected virtual global::System.Object readResolve(){return default(global::System.Object);}
        }
        public override bool equals(global::System.Object prm1){return default(bool);}
        public virtual byte[] getEncoded(global::java.lang.String prm1){return default(byte[]);}
        public override int hashCode(){return default(int);}
        public CertPath(global::java.lang.String prm1){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        protected virtual global::System.Object writeReplace(){return default(global::System.Object);}
        public global::java.util.List<Certificate>  Certificates { get; private set;}
        public byte[]  Encoded { get; private set;}
        public global::java.util.Iterator<global::java.lang.String>  Encodings { get; private set;}
        public global::java.lang.String  Type { get; private set;}
    }
}
