//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.annotation
{
    public partial class AnnotationFormatError : Error
    {
        public AnnotationFormatError(String prm1){}
        public AnnotationFormatError(String prm1, Throwable prm2){}
        public AnnotationFormatError(Throwable prm1){}
    }
}
