//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.annotation
{
    public partial interface Annotation
    {
        Class<Annotation> annotationType();
        bool equals(global::System.Object prm1);
        int hashCode();
        String toString();
    }
}
