//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.annotation
{
    public partial class ElementType : Enum<ElementType>
    {
        public static ElementType ANNOTATION_TYPE;
        public static ElementType CONSTRUCTOR;
        public static ElementType FIELD;
        public static ElementType LOCAL_VARIABLE;
        public static ElementType METHOD;
        public static ElementType PACKAGE;
        public static ElementType PARAMETER;
        public static ElementType TYPE;
        public ElementType(){}
        public static ElementType valueOf(String prm1){return default(ElementType);}
        public static ElementType[] values(){return default(ElementType[]);}
    }
}
