//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.annotation
{
    public partial class IncompleteAnnotationException : RuntimeException
    {
        public virtual Class<Annotation> annotationType(){return default(Class<Annotation>);}
        public virtual String elementName(){return default(String);}
        public IncompleteAnnotationException(Class<Annotation> prm1, String prm2){}
    }
}
