//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.annotation
{
    public partial interface Inherited : Annotation
    {
    }
}
