//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels.spi
{
    public abstract partial class AbstractSelectableChannel : SelectableChannel
    {
        public global::System.Object blockingLock(){return default(global::System.Object);}
        public SelectableChannel configureBlocking(bool prm1){return default(SelectableChannel);}
        protected void implCloseChannel(){}
        protected virtual void implCloseSelectableChannel(){}
        protected virtual void implConfigureBlocking(bool prm1){}
        public AbstractSelectableChannel(SelectorProvider prm1){}
        public SelectionKey keyFor(Selector prm1){return default(SelectionKey);}
        public SelectorProvider provider(){return default(SelectorProvider);}
        public SelectionKey register(Selector prm1, int prm2, global::System.Object prm3){return default(SelectionKey);}
        public bool  IsBlocking { get; private set;}
        public bool  IsRegistered { get; private set;}
    }
}
