//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.channels.spi
{
    public abstract partial class SelectorProvider : global::java.lang.Object
    {
        public virtual Channel inheritedChannel(){return default(Channel);}
        public SelectorProvider(){}
        public virtual DatagramChannel openDatagramChannel(global::java.net.ProtocolFamily prm1){return default(DatagramChannel);}
        public virtual DatagramChannel openDatagramChannel(){return default(DatagramChannel);}
        public virtual Pipe openPipe(){return default(Pipe);}
        public virtual AbstractSelector openSelector(){return default(AbstractSelector);}
        public virtual ServerSocketChannel openServerSocketChannel(){return default(ServerSocketChannel);}
        public virtual SocketChannel openSocketChannel(){return default(SocketChannel);}
        public static SelectorProvider provider(){return default(SelectorProvider);}
    }
}
