//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class BrokenBarrierException : global::java.lang.Exception
    {
        public BrokenBarrierException(){}
        public BrokenBarrierException(global::java.lang.String prm1){}
    }
}
