//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class CancellationException : global::java.lang.IllegalStateException
    {
        public CancellationException(){}
        public CancellationException(global::java.lang.String prm1){}
    }
}
