//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class ConcurrentLinkedQueue<E> : AbstractQueue<E>, Queue<E>, global::java.io.Serializable
    {
        public override bool add(E prm1){return default(bool);}
        public override bool addAll(Collection<E> prm1){return default(bool);}
        public override bool contains(global::System.Object prm1){return default(bool);}
        public override Iterator<E> iterator(){return default(Iterator<E>);}
        public ConcurrentLinkedQueue(){}
        public ConcurrentLinkedQueue(Collection<E> prm1){}
        public virtual bool offer(E prm1){return default(bool);}
        public virtual E peek(){return default(E);}
        public virtual E poll(){return default(E);}
        public override bool remove(global::System.Object prm1){return default(bool);}
        public override int size(){return default(int);}
        public override T[] toArray<T>(T[] prm1){return default(T[]);}
        public override global::System.Object[] toArray(){return default(global::System.Object[]);}
        public bool  IsEmpty { get; private set;}
    }
}
