//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class Exchanger<V> : global::java.lang.Object
    {
        public virtual V exchange(V prm1, long prm2, TimeUnit prm3){return default(V);}
        public virtual V exchange(V prm1){return default(V);}
        public Exchanger(){}
    }
}
