//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial interface Executor
    {
        void execute(global::java.lang.Runnable prm1);
    }
}
