//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class ForkJoinWorkerThread : global::java.lang.Thread
    {
        public ForkJoinWorkerThread(ForkJoinPool prm1){}
        protected virtual void onStart(){}
        protected virtual void onTermination(global::java.lang.Throwable prm1){}
        public override void run(){}
        public ForkJoinPool  Pool { get; private set;}
        public int  PoolIndex { get; private set;}
    }
}
