//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class PriorityBlockingQueue<E> : AbstractQueue<E>, BlockingQueue<E>, global::java.io.Serializable
    {
        public override bool add(E prm1){return default(bool);}
        public override void clear(){}
        public virtual Comparator<global::System.Object> comparator(){return default(Comparator<global::System.Object>);}
        public override bool contains(global::System.Object prm1){return default(bool);}
        public virtual int drainTo(Collection<global::System.Object> prm1, int prm2){return default(int);}
        public virtual int drainTo(Collection<global::System.Object> prm1){return default(int);}
        public override Iterator<E> iterator(){return default(Iterator<E>);}
        public PriorityBlockingQueue(Collection<E> prm1){}
        public PriorityBlockingQueue(int prm1, Comparator<global::System.Object> prm2){}
        public PriorityBlockingQueue(int prm1){}
        public PriorityBlockingQueue(){}
        public virtual bool offer(E prm1){return default(bool);}
        public virtual bool offer(E prm1, long prm2, TimeUnit prm3){return default(bool);}
        public virtual E peek(){return default(E);}
        public virtual E poll(){return default(E);}
        public virtual E poll(long prm1, TimeUnit prm2){return default(E);}
        public virtual void put(E prm1){}
        public virtual int remainingCapacity(){return default(int);}
        public override bool remove(global::System.Object prm1){return default(bool);}
        public override int size(){return default(int);}
        public virtual E take(){return default(E);}
        public override T[] toArray<T>(T[] prm1){return default(T[]);}
        public override global::System.Object[] toArray(){return default(global::System.Object[]);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
