//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class RejectedExecutionException : global::java.lang.RuntimeException
    {
        public RejectedExecutionException(global::java.lang.Throwable prm1){}
        public RejectedExecutionException(global::java.lang.String prm1, global::java.lang.Throwable prm2){}
        public RejectedExecutionException(global::java.lang.String prm1){}
        public RejectedExecutionException(){}
    }
}
