//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial interface RunnableFuture<V> : global::java.lang.Runnable, Future<V>
    {
    }
}
