//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class ThreadLocalRandom : Random
    {
        public ThreadLocalRandom(){}
        public static ThreadLocalRandom current(){return default(ThreadLocalRandom);}
        protected override int next(int prm1){return default(int);}
        public virtual double nextDouble(double prm1){return default(double);}
        public virtual double nextDouble(double prm1, double prm2){return default(double);}
        public virtual int nextInt(int prm1, int prm2){return default(int);}
        public virtual long nextLong(long prm1){return default(long);}
        public virtual long nextLong(long prm1, long prm2){return default(long);}
        public override void setSeed(long prm1){}
    }
}
