//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public abstract partial class TimeUnit : global::java.lang.Enum<TimeUnit>
    {
        public static TimeUnit DAYS;
        public static TimeUnit HOURS;
        public static TimeUnit MICROSECONDS;
        public static TimeUnit MILLISECONDS;
        public static TimeUnit MINUTES;
        public static TimeUnit NANOSECONDS;
        public static TimeUnit SECONDS;
        public TimeUnit(){}
        public virtual long convert(long prm1, TimeUnit prm2){return default(long);}
        public virtual void sleep(long prm1){}
        public virtual void timedJoin(global::java.lang.Thread prm1, long prm2){}
        public virtual void timedWait(global::System.Object prm1, long prm2){}
        public virtual long toDays(long prm1){return default(long);}
        public virtual long toHours(long prm1){return default(long);}
        public virtual long toMicros(long prm1){return default(long);}
        public virtual long toMillis(long prm1){return default(long);}
        public virtual long toMinutes(long prm1){return default(long);}
        public virtual long toNanos(long prm1){return default(long);}
        public virtual long toSeconds(long prm1){return default(long);}
        public static TimeUnit valueOf(global::java.lang.String prm1){return default(TimeUnit);}
        public static TimeUnit[] values(){return default(TimeUnit[]);}
    }
}
