//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial class TimeoutException : global::java.lang.Exception
    {
        public TimeoutException(){}
        public TimeoutException(global::java.lang.String prm1){}
    }
}
