//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.concurrent
{
    public partial interface TransferQueue<E> : BlockingQueue<E>
    {
        bool hasWaitingConsumer();
        void transfer(E prm1);
        bool tryTransfer(E prm1, long prm2, TimeUnit prm3);
        bool tryTransfer(E prm1);
        int  WaitingConsumerCount { get;}
    }
}
