//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file.attribute
{
    public partial interface FileAttributeView : AttributeView
    {
    }
}
