//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file.attribute
{
    public partial interface UserPrincipal : global::java.security.Principal
    {
    }
}
