//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class Bits : global::java.lang.Object
    {
        public Bits(){}
    }
}
