//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    public partial class BufferUnderflowException : global::java.lang.RuntimeException
    {
        public BufferUnderflowException(){}
    }
}
