//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    public abstract partial class Buffer : global::java.lang.Object
    {
        public Buffer(){}
        public virtual global::System.Object array(){return default(global::System.Object);}
        public virtual int arrayOffset(){return default(int);}
        public int capacity(){return default(int);}
        public Buffer clear(){return default(Buffer);}
        public Buffer flip(){return default(Buffer);}
        public virtual bool hasArray(){return default(bool);}
        public bool hasRemaining(){return default(bool);}
        public Buffer limit(int prm1){return default(Buffer);}
        public int limit(){return default(int);}
        public Buffer mark(){return default(Buffer);}
        public int position(){return default(int);}
        public Buffer position(int prm1){return default(Buffer);}
        public int remaining(){return default(int);}
        public Buffer reset(){return default(Buffer);}
        public Buffer rewind(){return default(Buffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
