//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    public partial class BufferOverflowException : global::java.lang.RuntimeException
    {
        public BufferOverflowException(){}
    }
}
