//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class ByteBufferAsLongBufferL : LongBuffer
    {
        public ByteBuffer bb;
        public int offset;
        public ByteBufferAsLongBufferL(){}
        public override LongBuffer asReadOnlyBuffer(){return default(LongBuffer);}
        public override LongBuffer compact(){return default(LongBuffer);}
        public override LongBuffer duplicate(){return default(LongBuffer);}
        public override long get(){return default(long);}
        public override long get(int prm1){return default(long);}
        protected virtual int ix(int prm1){return default(int);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override LongBuffer put(int prm1, long prm2){return default(LongBuffer);}
        public override LongBuffer put(long prm1){return default(LongBuffer);}
        public override LongBuffer slice(){return default(LongBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
