//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class ByteBufferAsDoubleBufferL : DoubleBuffer
    {
        public ByteBuffer bb;
        public int offset;
        public ByteBufferAsDoubleBufferL(){}
        public override DoubleBuffer asReadOnlyBuffer(){return default(DoubleBuffer);}
        public override DoubleBuffer compact(){return default(DoubleBuffer);}
        public override DoubleBuffer duplicate(){return default(DoubleBuffer);}
        public override double get(){return default(double);}
        public override double get(int prm1){return default(double);}
        protected virtual int ix(int prm1){return default(int);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override DoubleBuffer put(int prm1, double prm2){return default(DoubleBuffer);}
        public override DoubleBuffer put(double prm1){return default(DoubleBuffer);}
        public override DoubleBuffer slice(){return default(DoubleBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
