//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    public partial class ByteOrder : global::java.lang.Object
    {
        public static ByteOrder BIG_ENDIAN;
        public static ByteOrder LITTLE_ENDIAN;
        public ByteOrder(){}
        public static ByteOrder nativeOrder(){return default(ByteOrder);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
