//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class ByteBufferAsFloatBufferB : FloatBuffer
    {
        public ByteBuffer bb;
        public int offset;
        public ByteBufferAsFloatBufferB(){}
        public override FloatBuffer asReadOnlyBuffer(){return default(FloatBuffer);}
        public override FloatBuffer compact(){return default(FloatBuffer);}
        public override FloatBuffer duplicate(){return default(FloatBuffer);}
        public override float get(){return default(float);}
        public override float get(int prm1){return default(float);}
        protected virtual int ix(int prm1){return default(int);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override FloatBuffer put(int prm1, float prm2){return default(FloatBuffer);}
        public override FloatBuffer put(float prm1){return default(FloatBuffer);}
        public override FloatBuffer slice(){return default(FloatBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
