//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class ByteBufferAsCharBufferRL : ByteBufferAsCharBufferL
    {
        public ByteBufferAsCharBufferRL(){}
        public override CharBuffer asReadOnlyBuffer(){return default(CharBuffer);}
        public override CharBuffer compact(){return default(CharBuffer);}
        public override CharBuffer duplicate(){return default(CharBuffer);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override CharBuffer put(int prm1, char prm2){return default(CharBuffer);}
        public override CharBuffer put(char prm1){return default(CharBuffer);}
        public override CharBuffer slice(){return default(CharBuffer);}
        public override CharBuffer subSequence(int prm1, int prm2){return default(CharBuffer);}
        public override global::java.lang.String toString(int prm1, int prm2){return default(global::java.lang.String);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
