//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class DirectShortBufferRU : DirectShortBufferU, global::sun.nio.ch.DirectBuffer
    {
        public DirectShortBufferRU(){}
        public override ShortBuffer asReadOnlyBuffer(){return default(ShortBuffer);}
        public override ShortBuffer compact(){return default(ShortBuffer);}
        public override ShortBuffer duplicate(){return default(ShortBuffer);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override ShortBuffer put(ShortBuffer prm1){return default(ShortBuffer);}
        public override ShortBuffer put(int prm1, short prm2){return default(ShortBuffer);}
        public override ShortBuffer put(short prm1){return default(ShortBuffer);}
        public override ShortBuffer put(short[] prm1, int prm2, int prm3){return default(ShortBuffer);}
        public override ShortBuffer slice(){return default(ShortBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
