//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class DirectIntBufferRU : DirectIntBufferU, global::sun.nio.ch.DirectBuffer
    {
        public DirectIntBufferRU(){}
        public override IntBuffer asReadOnlyBuffer(){return default(IntBuffer);}
        public override IntBuffer compact(){return default(IntBuffer);}
        public override IntBuffer duplicate(){return default(IntBuffer);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override IntBuffer put(IntBuffer prm1){return default(IntBuffer);}
        public override IntBuffer put(int prm1, int prm2){return default(IntBuffer);}
        public override IntBuffer put(int prm1){return default(IntBuffer);}
        public override IntBuffer put(int[] prm1, int prm2, int prm3){return default(IntBuffer);}
        public override IntBuffer slice(){return default(IntBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
