//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class DirectLongBufferRS : DirectLongBufferS, global::sun.nio.ch.DirectBuffer
    {
        public DirectLongBufferRS(){}
        public override LongBuffer asReadOnlyBuffer(){return default(LongBuffer);}
        public override LongBuffer compact(){return default(LongBuffer);}
        public override LongBuffer duplicate(){return default(LongBuffer);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override LongBuffer put(LongBuffer prm1){return default(LongBuffer);}
        public override LongBuffer put(int prm1, long prm2){return default(LongBuffer);}
        public override LongBuffer put(long prm1){return default(LongBuffer);}
        public override LongBuffer put(long[] prm1, int prm2, int prm3){return default(LongBuffer);}
        public override LongBuffer slice(){return default(LongBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
