//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class DirectDoubleBufferRS : DirectDoubleBufferS, global::sun.nio.ch.DirectBuffer
    {
        public DirectDoubleBufferRS(){}
        public override DoubleBuffer asReadOnlyBuffer(){return default(DoubleBuffer);}
        public override DoubleBuffer compact(){return default(DoubleBuffer);}
        public override DoubleBuffer duplicate(){return default(DoubleBuffer);}
        public override ByteOrder order(){return default(ByteOrder);}
        public override DoubleBuffer put(DoubleBuffer prm1){return default(DoubleBuffer);}
        public override DoubleBuffer put(int prm1, double prm2){return default(DoubleBuffer);}
        public override DoubleBuffer put(double prm1){return default(DoubleBuffer);}
        public override DoubleBuffer put(double[] prm1, int prm2, int prm3){return default(DoubleBuffer);}
        public override DoubleBuffer slice(){return default(DoubleBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
