//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class HeapCharBufferR : HeapCharBuffer
    {
        public override CharBuffer asReadOnlyBuffer(){return default(CharBuffer);}
        public override CharBuffer compact(){return default(CharBuffer);}
        public override CharBuffer duplicate(){return default(CharBuffer);}
        public HeapCharBufferR(char[] prm1, int prm2, int prm3, int prm4, int prm5, int prm6) : base(default(char[]), default(int), default(int), default(int), default(int), default(int)){}
        public override ByteOrder order(){return default(ByteOrder);}
        public override CharBuffer put(char prm1){return default(CharBuffer);}
        public override CharBuffer put(int prm1, char prm2){return default(CharBuffer);}
        public override CharBuffer put(char[] prm1, int prm2, int prm3){return default(CharBuffer);}
        public override CharBuffer put(CharBuffer prm1){return default(CharBuffer);}
        public override CharBuffer slice(){return default(CharBuffer);}
        public override CharBuffer subSequence(int prm1, int prm2){return default(CharBuffer);}
        public bool  IsReadOnly { get; private set;}
    }
}
