//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class HeapShortBufferR : HeapShortBuffer
    {
        public override ShortBuffer asReadOnlyBuffer(){return default(ShortBuffer);}
        public override ShortBuffer compact(){return default(ShortBuffer);}
        public override ShortBuffer duplicate(){return default(ShortBuffer);}
        public HeapShortBufferR(short[] prm1, int prm2, int prm3, int prm4, int prm5, int prm6) : base(default(short[]), default(int), default(int), default(int), default(int), default(int)){}
        public override ByteOrder order(){return default(ByteOrder);}
        public override ShortBuffer put(short prm1){return default(ShortBuffer);}
        public override ShortBuffer put(int prm1, short prm2){return default(ShortBuffer);}
        public override ShortBuffer put(short[] prm1, int prm2, int prm3){return default(ShortBuffer);}
        public override ShortBuffer put(ShortBuffer prm1){return default(ShortBuffer);}
        public override ShortBuffer slice(){return default(ShortBuffer);}
        public bool  IsReadOnly { get; private set;}
    }
}
