//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class HeapLongBufferR : HeapLongBuffer
    {
        public override LongBuffer asReadOnlyBuffer(){return default(LongBuffer);}
        public override LongBuffer compact(){return default(LongBuffer);}
        public override LongBuffer duplicate(){return default(LongBuffer);}
        public HeapLongBufferR(long[] prm1, int prm2, int prm3, int prm4, int prm5, int prm6) : base(default(long[]), default(int), default(int), default(int), default(int), default(int)){}
        public override ByteOrder order(){return default(ByteOrder);}
        public override LongBuffer put(long prm1){return default(LongBuffer);}
        public override LongBuffer put(int prm1, long prm2){return default(LongBuffer);}
        public override LongBuffer put(long[] prm1, int prm2, int prm3){return default(LongBuffer);}
        public override LongBuffer put(LongBuffer prm1){return default(LongBuffer);}
        public override LongBuffer slice(){return default(LongBuffer);}
        public bool  IsReadOnly { get; private set;}
    }
}
