//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class HeapFloatBufferR : HeapFloatBuffer
    {
        public override FloatBuffer asReadOnlyBuffer(){return default(FloatBuffer);}
        public override FloatBuffer compact(){return default(FloatBuffer);}
        public override FloatBuffer duplicate(){return default(FloatBuffer);}
        public HeapFloatBufferR(float[] prm1, int prm2, int prm3, int prm4, int prm5, int prm6) : base(default(float[]), default(int), default(int), default(int), default(int), default(int)){}
        public override ByteOrder order(){return default(ByteOrder);}
        public override FloatBuffer put(float prm1){return default(FloatBuffer);}
        public override FloatBuffer put(int prm1, float prm2){return default(FloatBuffer);}
        public override FloatBuffer put(float[] prm1, int prm2, int prm3){return default(FloatBuffer);}
        public override FloatBuffer put(FloatBuffer prm1){return default(FloatBuffer);}
        public override FloatBuffer slice(){return default(FloatBuffer);}
        public bool  IsReadOnly { get; private set;}
    }
}
