//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    public partial class InvalidMarkException : global::java.lang.IllegalStateException
    {
        public InvalidMarkException(){}
    }
}
