//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio
{
    internal partial class StringCharBuffer : CharBuffer
    {
        public StringCharBuffer(){}
        public override CharBuffer asReadOnlyBuffer(){return default(CharBuffer);}
        public CharBuffer compact(){return default(CharBuffer);}
        public override CharBuffer duplicate(){return default(CharBuffer);}
        public char get(int prm1){return default(char);}
        public char get(){return default(char);}
        public override ByteOrder order(){return default(ByteOrder);}
        public CharBuffer put(int prm1, char prm2){return default(CharBuffer);}
        public CharBuffer put(char prm1){return default(CharBuffer);}
        public override CharBuffer slice(){return default(CharBuffer);}
        public CharBuffer subSequence(int prm1, int prm2){return default(CharBuffer);}
        public bool  IsDirect { get; private set;}
        public bool  IsReadOnly { get; private set;}
    }
}
