//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface DirectoryStream<T> : global::java.io.Closeable, global::java.lang.Iterable<T>
    {
        global::java.util.Iterator<T> iterator();
    }
}
