//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface DirectoryStream_Filter<T>
    {
        bool accept(T prm1);
    }
}
