//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public abstract partial class FileStore : global::java.lang.Object
    {
        public virtual global::System.Object getAttribute(global::java.lang.String prm1){return default(global::System.Object);}
        public virtual V getFileStoreAttributeView<V>(global::java.lang.Class<V> prm1){return default(V);}
        public FileStore(){}
        public virtual global::java.lang.String name(){return default(global::java.lang.String);}
        public virtual bool supportsFileAttributeView(global::java.lang.Class<global::java.nio.file.attribute.FileAttributeView> prm1){return default(bool);}
        public virtual bool supportsFileAttributeView(global::java.lang.String prm1){return default(bool);}
        public virtual global::java.lang.String type(){return default(global::java.lang.String);}
        public bool  IsReadOnly { get; private set;}
        public long  TotalSpace { get; private set;}
        public long  UnallocatedSpace { get; private set;}
        public long  UsableSpace { get; private set;}
    }
}
