//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface PathMatcher
    {
        bool matches(Path prm1);
    }
}
