//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface Watchable
    {
        WatchKey register(WatchService prm1, WatchEvent_Kind<global::System.Object>[] prm2, WatchEvent_Modifier[] prm3);
        WatchKey register(WatchService prm1, WatchEvent_Kind<global::System.Object>[] prm2);
    }
}
