//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface WatchEvent_Modifier
    {
        global::java.lang.String name();
    }
}
