//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.nio.file
{
    public partial interface WatchEvent_Kind<T>
    {
        global::java.lang.String name();
        global::java.lang.Class<T> type();
    }
}
