//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class Array : Object
    {
        public Array(){}
        public static global::System.Object get(global::System.Object prm1, int prm2){return default(global::System.Object);}
        public static bool getBoolean(global::System.Object prm1, int prm2){return default(bool);}
        public static byte getByte(global::System.Object prm1, int prm2){return default(byte);}
        public static char getChar(global::System.Object prm1, int prm2){return default(char);}
        public static double getDouble(global::System.Object prm1, int prm2){return default(double);}
        public static float getFloat(global::System.Object prm1, int prm2){return default(float);}
        public static int getInt(global::System.Object prm1, int prm2){return default(int);}
        public static int getLength(global::System.Object prm1){return default(int);}
        public static long getLong(global::System.Object prm1, int prm2){return default(long);}
        public static short getShort(global::System.Object prm1, int prm2){return default(short);}
        public static global::System.Object newInstance(Class<global::System.Object> prm1, int prm2){return default(global::System.Object);}
        public static global::System.Object newInstance(Class<global::System.Object> prm1, int[] prm2){return default(global::System.Object);}
        public static void set(global::System.Object prm1, int prm2, global::System.Object prm3){}
        public static void setBoolean(global::System.Object prm1, int prm2, bool prm3){}
        public static void setByte(global::System.Object prm1, int prm2, byte prm3){}
        public static void setChar(global::System.Object prm1, int prm2, char prm3){}
        public static void setDouble(global::System.Object prm1, int prm2, double prm3){}
        public static void setFloat(global::System.Object prm1, int prm2, float prm3){}
        public static void setInt(global::System.Object prm1, int prm2, int prm3){}
        public static void setLong(global::System.Object prm1, int prm2, long prm3){}
        public static void setShort(global::System.Object prm1, int prm2, short prm3){}
    }
}
