//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class Field : AccessibleObject, Member
    {
        public Field(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public virtual global::System.Object get(global::System.Object prm1){return default(global::System.Object);}
        public override T getAnnotation<T>(Class<T> prm1){return default(T);}
        public virtual bool getBoolean(global::System.Object prm1){return default(bool);}
        public virtual byte getByte(global::System.Object prm1){return default(byte);}
        public virtual char getChar(global::System.Object prm1){return default(char);}
        public virtual double getDouble(global::System.Object prm1){return default(double);}
        public virtual float getFloat(global::System.Object prm1){return default(float);}
        public virtual int getInt(global::System.Object prm1){return default(int);}
        public virtual long getLong(global::System.Object prm1){return default(long);}
        public virtual short getShort(global::System.Object prm1){return default(short);}
        public override int hashCode(){return default(int);}
        public virtual void set(global::System.Object prm1, global::System.Object prm2){}
        public virtual void setBoolean(global::System.Object prm1, bool prm2){}
        public virtual void setByte(global::System.Object prm1, byte prm2){}
        public virtual void setChar(global::System.Object prm1, char prm2){}
        public virtual void setDouble(global::System.Object prm1, double prm2){}
        public virtual void setFloat(global::System.Object prm1, float prm2){}
        public virtual void setInt(global::System.Object prm1, int prm2){}
        public virtual void setLong(global::System.Object prm1, long prm2){}
        public virtual void setShort(global::System.Object prm1, short prm2){}
        public virtual String toGenericString(){return default(String);}
        public override String toString(){return default(String);}
        public global::java.lang.annotation.Annotation[]  DeclaredAnnotations { get; private set;}
        public Class<global::System.Object>  DeclaringClass { get; private set;}
        public global::java.lang.reflect.Type  GenericType { get; private set;}
        public bool  IsEnumConstant { get; private set;}
        public bool  IsSynthetic { get; private set;}
        public int  Modifiers { get; private set;}
        public String  Name { get; private set;}
        public Class<global::System.Object>  Type { get; private set;}
    }
}
