//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial interface GenericArrayType : global::java.lang.reflect.Type
    {
        global::java.lang.reflect.Type  GenericComponentType { get;}
    }
}
