//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class GenericSignatureFormatError : ClassFormatError
    {
        public GenericSignatureFormatError(){}
    }
}
