//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial interface GenericDeclaration
    {
        TypeVariable<global::System.Object>[]  TypeParameters { get;}
    }
}
