//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class InvocationTargetException : ReflectiveOperationException
    {
        public InvocationTargetException(Throwable prm1, String prm2){}
        public InvocationTargetException(Throwable prm1){}
        public InvocationTargetException(){}
        public Throwable  Cause { get; private set;}
        public Throwable  TargetException { get; private set;}
    }
}
