//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial interface Member
    {
        Class<global::System.Object>  DeclaringClass { get;}
        bool  IsSynthetic { get;}
        int  Modifiers { get;}
        String  Name { get;}
    }
}
