//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class Method : AccessibleObject, GenericDeclaration, Member
    {
        public Method(){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override T getAnnotation<T>(Class<T> prm1){return default(T);}
        public override int hashCode(){return default(int);}
        public virtual global::System.Object invoke(global::System.Object prm1, global::System.Object[] prm2){return default(global::System.Object);}
        public virtual String toGenericString(){return default(String);}
        public override String toString(){return default(String);}
        public global::java.lang.annotation.Annotation[]  DeclaredAnnotations { get; private set;}
        public Class<global::System.Object>  DeclaringClass { get; private set;}
        public global::System.Object  DefaultValue { get; private set;}
        public Class<global::System.Object>[]  ExceptionTypes { get; private set;}
        public global::java.lang.reflect.Type[]  GenericExceptionTypes { get; private set;}
        public global::java.lang.reflect.Type[]  GenericParameterTypes { get; private set;}
        public global::java.lang.reflect.Type  GenericReturnType { get; private set;}
        public bool  IsBridge { get; private set;}
        public bool  IsSynthetic { get; private set;}
        public bool  IsVarArgs { get; private set;}
        public int  Modifiers { get; private set;}
        public String  Name { get; private set;}
        public global::java.lang.annotation.Annotation[][]  ParameterAnnotations { get; private set;}
        public Class<global::System.Object>[]  ParameterTypes { get; private set;}
        public Class<global::System.Object>  ReturnType { get; private set;}
        public TypeVariable<Method>[]  TypeParameters { get; private set;}
        TypeVariable<global::System.Object>[] GenericDeclaration.TypeParameters { get{ return default(TypeVariable<global::System.Object>[]); }}
    }
}
