//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial interface ParameterizedType : global::java.lang.reflect.Type
    {
        global::java.lang.reflect.Type[]  ActualTypeArguments { get;}
        global::java.lang.reflect.Type  OwnerType { get;}
        global::java.lang.reflect.Type  RawType { get;}
    }
}
