//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial class Proxy : Object, global::java.io.Serializable
    {
        public InvocationHandler h;
        public static InvocationHandler getInvocationHandler(global::System.Object prm1){return default(InvocationHandler);}
        public static Class<global::System.Object> getProxyClass(ClassLoader prm1, Class<global::System.Object>[] prm2){return default(Class<global::System.Object>);}
        public static bool isProxyClass(Class<global::System.Object> prm1){return default(bool);}
        public Proxy(InvocationHandler prm1){}
        public static global::System.Object newProxyInstance(ClassLoader prm1, Class<global::System.Object>[] prm2, InvocationHandler prm3){return default(global::System.Object);}
    }
}
