//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.lang.reflect
{
    public partial interface TypeVariable<D> : global::java.lang.reflect.Type
    {
        global::java.lang.reflect.Type[]  Bounds { get;}
        D  GenericDeclaration { get;}
        String  Name { get;}
    }
}
