//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.regex
{
    public partial interface MatchResult
    {
        int end(int prm1);
        int end();
        global::java.lang.String group();
        global::java.lang.String group(int prm1);
        int groupCount();
        int start(int prm1);
        int start();
    }
}
