//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.util.regex
{
    public partial class Pattern : global::java.lang.Object, global::java.io.Serializable
    {
        public static int CANON_EQ;
        public static int CASE_INSENSITIVE;
        public static int COMMENTS;
        public static int DOTALL;
        public static int LITERAL;
        public static int MULTILINE;
        public static int UNICODE_CASE;
        public static int UNICODE_CHARACTER_CLASS;
        public static int UNIX_LINES;
        public Pattern(){}
        public static Pattern compile(global::java.lang.String prm1){return default(Pattern);}
        public static Pattern compile(global::java.lang.String prm1, int prm2){return default(Pattern);}
        public virtual int flags(){return default(int);}
        public virtual Matcher matcher(global::java.lang.CharSequence prm1){return default(Matcher);}
        public static bool matches(global::java.lang.String prm1, global::java.lang.CharSequence prm2){return default(bool);}
        public virtual global::java.lang.String pattern(){return default(global::java.lang.String);}
        public static global::java.lang.String quote(global::java.lang.String prm1){return default(global::java.lang.String);}
        public virtual global::java.lang.String[] split(global::java.lang.CharSequence prm1, int prm2){return default(global::java.lang.String[]);}
        public virtual global::java.lang.String[] split(global::java.lang.CharSequence prm1){return default(global::java.lang.String[]);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
    }
}
