//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial class CodeSource : global::java.lang.Object, global::java.io.Serializable
    {
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public virtual bool implies(CodeSource prm1){return default(bool);}
        public CodeSource(global::java.net.URL prm1, global::java.security.cert.Certificate[] prm2){}
        public CodeSource(global::java.net.URL prm1, CodeSigner[] prm2){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.security.cert.Certificate[]  Certificates { get; private set;}
        public CodeSigner[]  CodeSigners { get; private set;}
        public global::java.net.URL  Location { get; private set;}
    }
}
