//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial interface Guard
    {
        void checkGuard(global::System.Object prm1);
    }
}
