//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial interface Key : global::java.io.Serializable
    {
        global::java.lang.String  Algorithm { get;}
        byte[]  Encoded { get;}
        global::java.lang.String  Format { get;}
    }
}
