//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public abstract partial class Permission : global::java.lang.Object, Guard, global::java.io.Serializable
    {
        public virtual void checkGuard(global::System.Object prm1){}
        public override bool equals(global::System.Object prm1){return default(bool);}
        public override int hashCode(){return default(int);}
        public virtual bool implies(Permission prm1){return default(bool);}
        public Permission(global::java.lang.String prm1){}
        public virtual PermissionCollection newPermissionCollection(){return default(PermissionCollection);}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.lang.String  Actions { get; private set;}
        public global::java.lang.String  Name { get; private set;}
    }
}
