//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public abstract partial class PermissionCollection : global::java.lang.Object, global::java.io.Serializable
    {
        public virtual void add(Permission prm1){}
        public virtual global::java.util.Enumeration<Permission> elements(){return default(global::java.util.Enumeration<Permission>);}
        public virtual bool implies(Permission prm1){return default(bool);}
        public PermissionCollection(){}
        public virtual void setReadOnly(){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public bool  IsReadOnly { get; private set;}
    }
}
