//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial interface PrivilegedAction<T>
    {
        T run();
    }
}
