//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial class ProtectionDomain : global::java.lang.Object
    {
        public virtual bool implies(Permission prm1){return default(bool);}
        public ProtectionDomain(CodeSource prm1, PermissionCollection prm2){}
        public ProtectionDomain(CodeSource prm1, PermissionCollection prm2, global::java.lang.ClassLoader prm3, Principal[] prm4){}
        public override global::java.lang.String toString(){return default(global::java.lang.String);}
        public global::java.lang.ClassLoader  ClassLoader { get; private set;}
        public CodeSource  CodeSource { get; private set;}
        public PermissionCollection  Permissions { get; private set;}
        public Principal[]  Principals { get; private set;}
    }
}
