//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial interface PublicKey : Key
    {
    }
}
