//***************************************************
//* This file was generated by JSharp
//***************************************************
namespace java.security
{
    public partial class SecureClassLoader : global::java.lang.ClassLoader
    {
        protected global::java.lang.Class<global::System.Object> defineClass(global::java.lang.String prm1, global::java.nio.ByteBuffer prm2, CodeSource prm3){return default(global::java.lang.Class<global::System.Object>);}
        protected global::java.lang.Class<global::System.Object> defineClass(global::java.lang.String prm1, byte[] prm2, int prm3, int prm4, CodeSource prm5){return default(global::java.lang.Class<global::System.Object>);}
        protected virtual PermissionCollection getPermissions(CodeSource prm1){return default(PermissionCollection);}
        public SecureClassLoader(global::java.lang.ClassLoader prm1){}
        public SecureClassLoader(){}
    }
}
